
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

// We need to make sure this is local to the package, or else it will
// be taken from any external linkage.
#if defined(_NUITKA_MODULE) && !defined(_NUITKA_CONSTANTS_FROM_RESOURCE) && !defined(__cplusplus)
const unsigned char constant_bin[0];
#endif

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_float_1_0;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_7;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_str_chr_42;
PyObject *const_str_chr_45;
PyObject *const_str_chr_58;
PyObject *const_str_chr_61;
PyObject *const_bytes_empty;
PyObject *const_int_pos_256;
PyObject *const_str_newline;
PyObject *const_str_plain__;
PyObject *const_str_plain_e;
PyObject *const_str_plain_i;
PyObject *const_str_plain_m;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_str_plain_cb;
PyObject *const_str_plain_ex;
PyObject *const_str_plain_gi;
PyObject *const_str_plain_id;
PyObject *const_str_plain_io;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_tb;
PyObject *const_str_plain_Bus;
PyObject *const_str_plain__gi;
PyObject *const_str_plain_add;
PyObject *const_str_plain_ans;
PyObject *const_str_plain_arg;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_bus;
PyObject *const_str_plain_cls;
PyObject *const_str_plain_do_;
PyObject *const_str_plain_doc;
PyObject *const_str_plain_end;
PyObject *const_str_plain_exc;
PyObject *const_str_plain_fun;
PyObject *const_str_plain_get;
PyObject *const_str_plain_gid;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_msg;
PyObject *const_str_plain_new;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_ret;
PyObject *const_str_plain_run;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_typ;
PyObject *const_str_plain_uid;
PyObject *const_str_plain_val;
PyObject *const_str_plain_zip;
PyObject *const_str_plain_Byte;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_attr;
PyObject *const_str_plain_auth;
PyObject *const_str_plain_bool;
PyObject *const_str_plain_conn;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dbus;
PyObject *const_str_plain_ddir;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_emit;
PyObject *const_str_plain_file;
PyObject *const_str_plain_func;
PyObject *const_str_plain_glib;
PyObject *const_str_plain_info;
PyObject *const_str_plain_is_a;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_list;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_prob;
PyObject *const_str_plain_read;
PyObject *const_str_plain_recv;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_rule;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_uuid;
PyObject *const_str_plain_void;
PyObject *const_str_plain_warn;
PyObject *const_float_minus_0_0;
PyObject *const_float_minus_1_0;
PyObject *const_str_plain_Array;
PyObject *const_str_plain_ERROR;
PyObject *const_str_plain_False;
PyObject *const_str_plain_GEnum;
PyObject *const_str_plain_GTKIO;
PyObject *const_str_plain_GType;
PyObject *const_str_plain_Int16;
PyObject *const_str_plain_Int32;
PyObject *const_str_plain_Int64;
PyObject *const_str_plain_bases;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_chown;
PyObject *const_str_plain_close;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_dict_;
PyObject *const_str_plain_error;
PyObject *const_str_plain_field;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_float;
PyObject *const_str_plain_iface;
PyObject *const_str_plain_items;
PyObject *const_str_plain_klass;
PyObject *const_str_plain_level;
PyObject *const_str_plain_limit;
PyObject *const_str_plain_long_;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_match;
PyObject *const_str_plain_owner;
PyObject *const_str_plain_print;
PyObject *const_str_plain_proxy;
PyObject *const_str_plain_range;
PyObject *const_str_plain_split;
PyObject *const_str_plain_strip;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_tools;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_type_;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_watch;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_Double;
PyObject *const_str_plain_GBoxed;
PyObject *const_str_plain_GFlags;
PyObject *const_str_plain_NewtIO;
PyObject *const_str_plain_String;
PyObject *const_str_plain_Struct;
PyObject *const_str_plain_TextIO;
PyObject *const_str_plain_UInt16;
PyObject *const_str_plain_UInt32;
PyObject *const_str_plain_UInt64;
PyObject *const_str_plain__proxy;
PyObject *const_str_plain_append;
PyObject *const_str_plain_create;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_delete;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_extend;
PyObject *const_str_plain_format;
PyObject *const_str_plain_g_type;
PyObject *const_str_plain_getpid;
PyObject *const_str_plain_getter;
PyObject *const_str_plain_getuid;
PyObject *const_str_plain_ignore;
PyObject *const_str_plain_is_py2;
PyObject *const_str_plain_is_py3;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_member;
PyObject *const_str_plain_method;
PyObject *const_str_plain_module;
PyObject *const_str_plain_object;
PyObject *const_str_plain_origin;
PyObject *const_str_plain_pytype;
PyObject *const_str_plain_reason;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_report;
PyObject *const_str_plain_result;
PyObject *const_str_plain_rsplit;
PyObject *const_str_plain_screen;
PyObject *const_str_plain_setter;
PyObject *const_str_plain_socket;
PyObject *const_str_plain_syslog;
PyObject *const_str_plain_system;
PyObject *const_str_plain_update;
PyObject *const_tuple_none_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_AF_UNIX;
PyObject *const_str_plain_Boolean;
PyObject *const_str_plain_GObject;
PyObject *const_str_plain_SHUT_WR;
PyObject *const_str_plain_Unknown;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___dir__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___get__;
PyObject *const_str_plain___new__;
PyObject *const_str_plain___set__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain__compat;
PyObject *const_str_plain__logger;
PyObject *const_str_plain_abspath;
PyObject *const_str_plain_acquire;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_connect;
PyObject *const_str_plain_delattr;
PyObject *const_str_plain_duphash;
PyObject *const_str_plain_getattr;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_gobject;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_isdigit;
PyObject *const_str_plain_logging;
PyObject *const_str_plain_matches;
PyObject *const_str_plain_modules;
PyObject *const_str_plain_pkgutil;
PyObject *const_str_plain_private;
PyObject *const_str_plain_problem;
PyObject *const_str_plain_proxies;
PyObject *const_str_plain_release;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_sendall;
PyObject *const_str_plain_timeout;
PyObject *const_str_plain_unicode;
PyObject *const_str_plain_version;
PyObject *const_str_plain_weakref;
PyObject *const_str_plain_wrapper;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_TYPE_INT;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___info__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain__probdir;
PyObject *const_str_plain_bus_name;
PyObject *const_str_plain_callable;
PyObject *const_str_plain_callback;
PyObject *const_str_plain_datetime;
PyObject *const_str_plain_del_item;
PyObject *const_str_plain_endswith;
PyObject *const_str_plain_exc_info;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_funcName;
PyObject *const_str_plain_get_item;
PyObject *const_str_plain_get_name;
PyObject *const_str_plain_get_size;
PyObject *const_str_plain_importer;
PyObject *const_str_plain_instance;
PyObject *const_str_plain_keywords;
PyObject *const_str_plain_list_all;
PyObject *const_str_plain_mainloop;
PyObject *const_str_plain_override;
PyObject *const_str_plain_property;
PyObject *const_str_plain_set_item;
PyObject *const_str_plain_shutdown;
PyObject *const_str_plain_strftime;
PyObject *const_str_plain_warnings;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain_ByteArray;
PyObject *const_str_plain_Interface;
PyObject *const_str_plain_Signature;
PyObject *const_str_plain_SystemBus;
PyObject *const_str_plain_TYPE_CHAR;
PyObject *const_str_plain_TYPE_ENUM;
PyObject *const_str_plain_TYPE_LONG;
PyObject *const_str_plain_TYPE_NONE;
PyObject *const_str_plain_TYPE_STRV;
PyObject *const_str_plain_TYPE_UINT;
PyObject *const_str_plain_VFuncInfo;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain___gtype__;
PyObject *const_str_plain___slots__;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_exception;
PyObject *const_str_plain_getLogger;
PyObject *const_str_plain_get_proxy;
PyObject *const_str_plain_get_value;
PyObject *const_str_plain_importlib;
PyObject *const_str_plain_interface;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_namespace;
PyObject *const_str_plain_overrides;
PyObject *const_str_plain_signature;
PyObject *const_str_plain_threading;
PyObject *const_str_plain_traceback;
PyObject *const_tuple_str_dot_tuple;
PyObject *const_slice_none_none_none;
PyObject *const_str_plain_BUS_SYSTEM;
PyObject *const_str_plain_Connection;
PyObject *const_str_plain_Dictionary;
PyObject *const_str_plain_GInterface;
PyObject *const_str_plain_LOCAL_PATH;
PyObject *const_str_plain_ModuleType;
PyObject *const_str_plain_ObjectInfo;
PyObject *const_str_plain_ObjectPath;
PyObject *const_str_plain_Repository;
PyObject *const_str_plain_SessionBus;
PyObject *const_str_plain_StarterBus;
PyObject *const_str_plain_StructInfo;
PyObject *const_str_plain_StructMeta;
PyObject *const_str_plain_TYPE_BOXED;
PyObject *const_str_plain_TYPE_FLAGS;
PyObject *const_str_plain_TYPE_FLOAT;
PyObject *const_str_plain_TYPE_GTYPE;
PyObject *const_str_plain_TYPE_INT64;
PyObject *const_str_plain_TYPE_PARAM;
PyObject *const_str_plain_TYPE_UCHAR;
PyObject *const_str_plain_TYPE_ULONG;
PyObject *const_str_plain_UTF8String;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain__constants;
PyObject *const_str_plain__persisted;
PyObject *const_str_plain_call_async;
PyObject *const_str_plain_exceptions;
PyObject *const_str_plain_executable;
PyObject *const_str_plain_get_g_type;
PyObject *const_str_plain_get_object;
PyObject *const_str_plain_identifier;
PyObject *const_str_plain_introspect;
PyObject *const_str_plain_isinstance;
PyObject *const_str_plain_issubclass;
PyObject *const_str_plain_problemify;
PyObject *const_str_plain_pyanaconda;
PyObject *const_str_plain_repository;
PyObject *const_str_plain_setdefault;
PyObject *const_str_plain_settimeout;
PyObject *const_str_plain_stacklevel;
PyObject *const_str_plain_startswith;
PyObject *const_tuple_type_str_tuple;
PyObject *const_str_plain_AuthFailure;
PyObject *const_str_plain_BUS_SESSION;
PyObject *const_str_plain_BUS_STARTER;
PyObject *const_str_plain_GObjectMeta;
PyObject *const_str_plain_HAVE_POLKIT;
PyObject *const_str_plain_ImportError;
PyObject *const_str_plain_LOCAL_IFACE;
PyObject *const_str_plain_ProxyObject;
PyObject *const_str_plain_PyGIWarning;
PyObject *const_str_plain_SOCK_STREAM;
PyObject *const_str_plain_TYPE_DOUBLE;
PyObject *const_str_plain_TYPE_OBJECT;
PyObject *const_str_plain_TYPE_STRING;
PyObject *const_str_plain_TYPE_SYSTEM;
PyObject *const_str_plain_TYPE_UINT64;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain__connection;
PyObject *const_str_plain_basicConfig;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_collections;
PyObject *const_str_plain_extend_path;
PyObject *const_str_plain_get_default;
PyObject *const_str_plain_get_methods;
PyObject *const_str_plain_get_version;
PyObject *const_str_plain_method_info;
PyObject *const_str_plain_object_path;
PyObject *const_str_plain_signal_name;
PyObject *const_tuple_int_pos_5_tuple;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_str_plain_CallableInfo;
PyObject *const_str_plain_ErrorMessage;
PyObject *const_str_plain_FunctionInfo;
PyObject *const_str_plain_TYPE_BOOLEAN;
PyObject *const_str_plain_TYPE_INVALID;
PyObject *const_str_plain_TYPE_POINTER;
PyObject *const_str_plain_TYPE_SESSION;
PyObject *const_str_plain_TYPE_STARTER;
PyObject *const_str_plain_TYPE_VARIANT;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_has_location;
PyObject *const_str_plain_problem_data;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_string_types;
PyObject *const_str_plain_threads_init;
PyObject *const_str_plain_utf8_strings;
PyObject *const_str_plain_version_info;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_tuple_true_false_tuple;
PyObject *const_str_plain_BusConnection;
PyObject *const_str_plain_DBusException;
PyObject *const_str_plain_DBusGMainLoop;
PyObject *const_str_plain_InterfaceInfo;
PyObject *const_str_plain_PROBLEM_TYPES;
PyObject *const_str_plain_SignalMessage;
PyObject *const_str_plain_TYPE_PYOBJECT;
PyObject *const_str_plain___docformat__;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain_call_blocking;
PyObject *const_str_plain_error_handler;
PyObject *const_str_plain_fromtimestamp;
PyObject *const_str_plain_get_arguments;
PyObject *const_str_plain_get_dbus_name;
PyObject *const_str_plain_get_interface;
PyObject *const_str_plain_get_namespace;
PyObject *const_str_plain_import_module;
PyObject *const_str_plain_named_service;
PyObject *const_str_plain_reply_handler;
PyObject *const_tuple_int_pos_256_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_AttributeError;
PyObject *const_str_plain_InvalidProblem;
PyObject *const_str_plain_ProblemWatcher;
PyObject *const_str_plain_TYPE_INTERFACE;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain__dbus_bindings;
PyObject *const_str_plain_dbus_interface;
PyObject *const_str_plain_is_constructor;
PyObject *const_str_plain_load_overrides;
PyObject *const_slice_int_pos_1_none_none;
PyObject *const_slice_int_pos_3_none_none;
PyObject *const_slice_none_int_pos_3_none;
PyObject *const_str_plain_BUS_DAEMON_NAME;
PyObject *const_str_plain_BUS_DAEMON_PATH;
PyObject *const_str_plain_DynamicImporter;
PyObject *const_str_plain_ValidationError;
PyObject *const_str_plain___annotations__;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_absolute_import;
PyObject *const_str_plain_install_signals;
PyObject *const_str_plain_require_version;
PyObject *const_tuple_str_plain__gi_tuple;
PyObject *const_str_plain_BUS_DAEMON_IFACE;
PyObject *const_str_plain_ProxyObjectClass;
PyObject *const_str_plain_handler_function;
PyObject *const_str_plain_reStructuredText;
PyObject *const_str_plain_restructuredtext;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_tuple_str_plain_void_tuple;
PyObject *const_tuple_str_plain_warn_tuple;
PyObject *const_tuple_type_Exception_tuple;
PyObject *const_str_plain_MethodCallMessage;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_require_main_loop;
PyObject *const_str_plain_validate_bus_name;
PyObject *const_str_plain_DeprecationWarning;
PyObject *const_str_plain__require_main_loop;
PyObject *const_str_plain_enumerate_versions;
PyObject *const_str_plain_install_properties;
PyObject *const_tuple_str_plain_is_py2_tuple;
PyObject *const_str_plain_MethodReturnMessage;
PyObject *const_str_plain_NameExistsException;
PyObject *const_str_plain_ValidationException;
PyObject *const_str_plain_activate_name_owner;
PyObject *const_str_plain_add_signal_receiver;
PyObject *const_str_plain_generate_doc_string;
PyObject *const_str_plain_get_problem_watcher;
PyObject *const_str_plain_validate_error_name;
PyObject *const_tuple_str_dot_int_pos_1_tuple;
PyObject *const_tuple_str_plain_GObject_tuple;
PyObject *const_str_plain_INTROSPECTABLE_IFACE;
PyObject *const_str_plain_get_required_version;
PyObject *const_str_plain_introspection_module;
PyObject *const_str_plain_validate_member_name;
PyObject *const_str_plain_validate_object_path;
PyObject *const_str_plain_DEFAULT_DUMP_LOCATION;
PyObject *const_str_plain_set_sender_name_owner;
PyObject *const_tuple_int_pos_3_int_pos_3_tuple;
PyObject *const_tuple_none_none_none_none_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_str_plain_PyGIDeprecationWarning;
PyObject *const_str_plain_UnknownMethodException;
PyObject *const_str_plain__clean_up_signal_match;
PyObject *const_tuple_str_plain_UTF8String_tuple;
PyObject *const_str_plain_validate_interface_name;
PyObject *const_tuple_str_plain_PyGIWarning_tuple;
PyObject *const_tuple_str_plain_extend_path_tuple;
PyObject *const_str_plain_DBUS_START_REPLY_SUCCESS;
PyObject *const_str_plain_get_introspection_module;
PyObject *const_tuple_str_chr_45_str_plain___tuple;
PyObject *const_str_plain_follow_name_owner_changes;
PyObject *const_tuple_str_plain_BusConnection_tuple;
PyObject *const_tuple_str_plain_DBusException_tuple;
PyObject *const_str_plain_process_introspection_data;
PyObject *const_str_plain_submodule_search_locations;
PyObject *const_dict_f154c9a58c9419d7e391901d7b7fe49e;
PyObject *const_str_plain_IntrospectionParserException;
PyObject *const_str_plain_MissingErrorHandlerException;
PyObject *const_str_plain_MissingReplyHandlerException;
PyObject *const_str_plain_HANDLER_RESULT_NOT_YET_HANDLED;
PyObject *const_tuple_str_plain_named_service_none_tuple;
PyObject *const_tuple_str_plain_self_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_path_tuple;
PyObject *const_str_plain_DBUS_START_REPLY_ALREADY_RUNNING;
PyObject *const_str_digest_09d63a5a61044765cbef1a09e46446f1;
PyObject *const_str_digest_0b385b2a67f6700b8faf677cdd479207;
PyObject *const_str_digest_176045277faffdb215e36349ee6bf75e;
PyObject *const_str_digest_18c67c412066bef703396d613a159b4d;
PyObject *const_str_digest_1b131d6ac44490cf7b663211212d8dfa;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_286d73d90a388265c9abc0d24ef29c6f;
PyObject *const_str_digest_2dddc6e15ab2dcfb5a2b2205b5654fb4;
PyObject *const_str_digest_3aa5bee4de9b0149ae46ffed8a38c6b4;
PyObject *const_str_digest_3cc8fcb05b60f7b9437930cdc441ce30;
PyObject *const_str_digest_4289e46f026bf0dd92edd4764f9ca580;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_6090a95f7b926ecd6061b143b7cad52f;
PyObject *const_str_digest_62223e4c0fc7bcb5885146e43f1fb665;
PyObject *const_str_digest_66f7aeb02c13e91a30a18f0ea911888b;
PyObject *const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_79ed2cac4e638f0656fd263c1190bdb0;
PyObject *const_str_digest_8e2db9d493d0360a27a3bf19583a3201;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a70d2bed936523093700e5558854519a;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b0cc034d9177fde48a3b44ac122139d9;
PyObject *const_str_digest_b45a3c6f685a3991de51197626bab5ca;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d7a2d3682b691f7fb6d75512d991b529;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_e48610c30fffad33f2054d9dca0792b3;
PyObject *const_str_digest_ec911d7d8aa19d9c1e00a67b34952d6e;
PyObject *const_str_digest_f570069e0d46f80dd06443468800a290;
PyObject *const_str_digest_fcf040720b88d60da4ce975010c44a3a;
PyObject *const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0;
PyObject *const_tuple_str_plain_args_str_plain_kwargs_tuple;
PyObject *const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple;
PyObject *const_tuple_str_plain_PyGIDeprecationWarning_tuple;
PyObject *const_tuple_str_plain_self_str_plain_bus_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_instance_tuple;
PyObject *const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple;
PyObject *const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple;

static void _createGlobalConstants(void) {
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong(0ul);
    const_str_dot = UNSTREAM_STRING_ASCII(&constant_bin[ 10936 ], 1, 0);
    const_float_0_0 = UNSTREAM_FLOAT(&constant_bin[ 95538 ]);
    const_float_1_0 = UNSTREAM_FLOAT(&constant_bin[ 95546 ]);
    const_int_neg_1 = PyLong_FromLong(-1l);
    const_int_pos_1 = PyLong_FromUnsignedLong(1ul);
    const_int_pos_2 = PyLong_FromUnsignedLong(2ul);
    const_int_pos_3 = PyLong_FromUnsignedLong(3ul);
    const_int_pos_4 = PyLong_FromUnsignedLong(4ul);
    const_int_pos_5 = PyLong_FromUnsignedLong(5ul);
    const_int_pos_7 = PyLong_FromUnsignedLong(7ul);
    const_str_empty = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 0, 0);
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert(PyDict_Size(const_dict_empty) == 0);
    const_str_chr_42 = UNSTREAM_STRING_ASCII(&constant_bin[ 12605 ], 1, 0);
    const_str_chr_45 = UNSTREAM_STRING_ASCII(&constant_bin[ 11643 ], 1, 0);
    const_str_chr_58 = UNSTREAM_STRING_ASCII(&constant_bin[ 12702 ], 1, 0);
    const_str_chr_61 = UNSTREAM_STRING_ASCII(&constant_bin[ 24317 ], 1, 0);
    const_bytes_empty = UNSTREAM_BYTES(&constant_bin[ 0 ], 0);
    const_int_pos_256 = PyLong_FromUnsignedLong(256ul);
    const_str_newline = UNSTREAM_STRING_ASCII(&constant_bin[ 15889 ], 1, 0);
    const_str_plain__ = UNSTREAM_STRING_ASCII(&constant_bin[ 233 ], 1, 1);
    const_str_plain_e = UNSTREAM_STRING_ASCII(&constant_bin[ 3 ], 1, 1);
    const_str_plain_i = UNSTREAM_STRING_ASCII(&constant_bin[ 13 ], 1, 1);
    const_str_plain_m = UNSTREAM_STRING_ASCII(&constant_bin[ 2 ], 1, 1);
    const_str_plain_s = UNSTREAM_STRING_ASCII(&constant_bin[ 14 ], 1, 1);
    const_str_plain_t = UNSTREAM_STRING_ASCII(&constant_bin[ 18 ], 1, 1);
    const_str_plain_x = UNSTREAM_STRING_ASCII(&constant_bin[ 803 ], 1, 1);
    const_tuple_empty = PyTuple_New(0);
    const_str_plain_cb = UNSTREAM_STRING_ASCII(&constant_bin[ 31881 ], 2, 1);
    const_str_plain_ex = UNSTREAM_STRING_ASCII(&constant_bin[ 802 ], 2, 1);
    const_str_plain_gi = UNSTREAM_STRING_ASCII(&constant_bin[ 1708 ], 2, 1);
    const_str_plain_id = UNSTREAM_STRING_ASCII(&constant_bin[ 1517 ], 2, 1);
    const_str_plain_io = UNSTREAM_STRING_ASCII(&constant_bin[ 808 ], 2, 1);
    const_str_plain_os = UNSTREAM_STRING_ASCII(&constant_bin[ 145 ], 2, 1);
    const_str_plain_rb = UNSTREAM_STRING_ASCII(&constant_bin[ 13825 ], 2, 1);
    const_str_plain_tb = UNSTREAM_STRING_ASCII(&constant_bin[ 24355 ], 2, 1);
    const_str_plain_Bus = UNSTREAM_STRING_ASCII(&constant_bin[ 960 ], 3, 1);
    const_str_plain__gi = UNSTREAM_STRING_ASCII(&constant_bin[ 3508 ], 3, 1);
    const_str_plain_add = UNSTREAM_STRING_ASCII(&constant_bin[ 5805 ], 3, 1);
    const_str_plain_ans = UNSTREAM_STRING_ASCII(&constant_bin[ 5973 ], 3, 1);
    const_str_plain_arg = UNSTREAM_STRING_ASCII(&constant_bin[ 31620 ], 3, 1);
    const_str_plain_buf = UNSTREAM_STRING_ASCII(&constant_bin[ 30615 ], 3, 1);
    const_str_plain_bus = UNSTREAM_STRING_ASCII(&constant_bin[ 1523 ], 3, 1);
    const_str_plain_cls = UNSTREAM_STRING_ASCII(&constant_bin[ 26770 ], 3, 1);
    const_str_plain_do_ = UNSTREAM_STRING_ASCII(&constant_bin[ 62124 ], 3, 1);
    const_str_plain_doc = UNSTREAM_STRING_ASCII(&constant_bin[ 4960 ], 3, 1);
    const_str_plain_end = UNSTREAM_STRING_ASCII(&constant_bin[ 671 ], 3, 1);
    const_str_plain_exc = UNSTREAM_STRING_ASCII(&constant_bin[ 802 ], 3, 1);
    const_str_plain_fun = UNSTREAM_STRING_ASCII(&constant_bin[ 4971 ], 3, 1);
    const_str_plain_get = UNSTREAM_STRING_ASCII(&constant_bin[ 1203 ], 3, 1);
    const_str_plain_gid = UNSTREAM_STRING_ASCII(&constant_bin[ 76144 ], 3, 1);
    const_str_plain_int = UNSTREAM_STRING_ASCII(&constant_bin[ 2120 ], 3, 1);
    const_str_plain_key = UNSTREAM_STRING_ASCII(&constant_bin[ 10915 ], 3, 1);
    const_str_plain_len = UNSTREAM_STRING_ASCII(&constant_bin[ 8697 ], 3, 1);
    const_str_plain_map = UNSTREAM_STRING_ASCII(&constant_bin[ 10879 ], 3, 1);
    const_str_plain_msg = UNSTREAM_STRING_ASCII(&constant_bin[ 43444 ], 3, 1);
    const_str_plain_new = UNSTREAM_STRING_ASCII(&constant_bin[ 5845 ], 3, 1);
    const_str_plain_pop = UNSTREAM_STRING_ASCII(&constant_bin[ 95554 ], 3, 1);
    const_str_plain_ret = UNSTREAM_STRING_ASCII(&constant_bin[ 26557 ], 3, 1);
    const_str_plain_run = UNSTREAM_STRING_ASCII(&constant_bin[ 9709 ], 3, 1);
    const_str_plain_str = UNSTREAM_STRING_ASCII(&constant_bin[ 3406 ], 3, 1);
    const_str_plain_sum = UNSTREAM_STRING_ASCII(&constant_bin[ 18360 ], 3, 1);
    const_str_plain_sys = UNSTREAM_STRING_ASCII(&constant_bin[ 204 ], 3, 1);
    const_str_plain_typ = UNSTREAM_STRING_ASCII(&constant_bin[ 3413 ], 3, 1);
    const_str_plain_uid = UNSTREAM_STRING_ASCII(&constant_bin[ 9898 ], 3, 1);
    const_str_plain_val = UNSTREAM_STRING_ASCII(&constant_bin[ 1514 ], 3, 1);
    const_str_plain_zip = UNSTREAM_STRING_ASCII(&constant_bin[ 95557 ], 3, 1);
    const_str_plain_Byte = UNSTREAM_STRING_ASCII(&constant_bin[ 26118 ], 4, 1);
    const_str_plain_args = UNSTREAM_STRING_ASCII(&constant_bin[ 38494 ], 4, 1);
    const_str_plain_argv = UNSTREAM_STRING_ASCII(&constant_bin[ 85533 ], 4, 1);
    const_str_plain_attr = UNSTREAM_STRING_ASCII(&constant_bin[ 6616 ], 4, 1);
    const_str_plain_auth = UNSTREAM_STRING_ASCII(&constant_bin[ 51636 ], 4, 1);
    const_str_plain_bool = UNSTREAM_STRING_ASCII(&constant_bin[ 7726 ], 4, 1);
    const_str_plain_conn = UNSTREAM_STRING_ASCII(&constant_bin[ 1207 ], 4, 1);
    const_str_plain_copy = UNSTREAM_STRING_ASCII(&constant_bin[ 63590 ], 4, 1);
    const_str_plain_data = UNSTREAM_STRING_ASCII(&constant_bin[ 3103 ], 4, 1);
    const_str_plain_dbus = UNSTREAM_STRING_ASCII(&constant_bin[ 2794 ], 4, 1);
    const_str_plain_ddir = UNSTREAM_STRING_ASCII(&constant_bin[ 79492 ], 4, 1);
    const_str_plain_dict = UNSTREAM_STRING_ASCII(&constant_bin[ 7314 ], 4, 1);
    const_str_plain_emit = UNSTREAM_STRING_ASCII(&constant_bin[ 39544 ], 4, 1);
    const_str_plain_file = UNSTREAM_STRING_ASCII(&constant_bin[ 3669 ], 4, 1);
    const_str_plain_func = UNSTREAM_STRING_ASCII(&constant_bin[ 4971 ], 4, 1);
    const_str_plain_glib = UNSTREAM_STRING_ASCII(&constant_bin[ 47151 ], 4, 1);
    const_str_plain_info = UNSTREAM_STRING_ASCII(&constant_bin[ 3315 ], 4, 1);
    const_str_plain_is_a = UNSTREAM_STRING_ASCII(&constant_bin[ 95560 ], 4, 1);
    const_str_plain_iter = UNSTREAM_STRING_ASCII(&constant_bin[ 43613 ], 4, 1);
    const_str_plain_join = UNSTREAM_STRING_ASCII(&constant_bin[ 95564 ], 4, 1);
    const_str_plain_keys = UNSTREAM_STRING_ASCII(&constant_bin[ 42612 ], 4, 1);
    const_str_plain_list = UNSTREAM_STRING_ASCII(&constant_bin[ 24599 ], 4, 1);
    const_str_plain_name = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 4, 1);
    const_str_plain_open = UNSTREAM_STRING_ASCII(&constant_bin[ 8722 ], 4, 1);
    const_str_plain_path = UNSTREAM_STRING_ASCII(&constant_bin[ 737 ], 4, 1);
    const_str_plain_prob = UNSTREAM_STRING_ASCII(&constant_bin[ 8611 ], 4, 1);
    const_str_plain_read = UNSTREAM_STRING_ASCII(&constant_bin[ 2288 ], 4, 1);
    const_str_plain_recv = UNSTREAM_STRING_ASCII(&constant_bin[ 95568 ], 4, 1);
    const_str_plain_repr = UNSTREAM_STRING_ASCII(&constant_bin[ 1373 ], 4, 1);
    const_str_plain_rule = UNSTREAM_STRING_ASCII(&constant_bin[ 34176 ], 4, 1);
    const_str_plain_self = UNSTREAM_STRING_ASCII(&constant_bin[ 29142 ], 4, 1);
    const_str_plain_send = UNSTREAM_STRING_ASCII(&constant_bin[ 670 ], 4, 1);
    const_str_plain_site = UNSTREAM_STRING_ASCII(&constant_bin[ 24797 ], 4, 1);
    const_str_plain_time = UNSTREAM_STRING_ASCII(&constant_bin[ 7177 ], 4, 1);
    const_str_plain_type = UNSTREAM_STRING_ASCII(&constant_bin[ 3413 ], 4, 1);
    const_str_plain_uuid = UNSTREAM_STRING_ASCII(&constant_bin[ 9897 ], 4, 1);
    const_str_plain_void = UNSTREAM_STRING_ASCII(&constant_bin[ 95572 ], 4, 1);
    const_str_plain_warn = UNSTREAM_STRING_ASCII(&constant_bin[ 5497 ], 4, 1);
    const_float_minus_0_0 = UNSTREAM_FLOAT(&constant_bin[ 95576 ]);
    const_float_minus_1_0 = UNSTREAM_FLOAT(&constant_bin[ 95584 ]);
    const_str_plain_Array = UNSTREAM_STRING_ASCII(&constant_bin[ 26122 ], 5, 1);
    const_str_plain_ERROR = UNSTREAM_STRING_ASCII(&constant_bin[ 46694 ], 5, 1);
    const_str_plain_False = UNSTREAM_STRING_ASCII(&constant_bin[ 39862 ], 5, 1);
    const_str_plain_GEnum = UNSTREAM_STRING_ASCII(&constant_bin[ 95592 ], 5, 1);
    const_str_plain_GTKIO = UNSTREAM_STRING_ASCII(&constant_bin[ 82703 ], 5, 1);
    const_str_plain_GType = UNSTREAM_STRING_ASCII(&constant_bin[ 62817 ], 5, 1);
    const_str_plain_Int16 = UNSTREAM_STRING_ASCII(&constant_bin[ 26155 ], 5, 1);
    const_str_plain_Int32 = UNSTREAM_STRING_ASCII(&constant_bin[ 26170 ], 5, 1);
    const_str_plain_Int64 = UNSTREAM_STRING_ASCII(&constant_bin[ 26185 ], 5, 1);
    const_str_plain_bases = UNSTREAM_STRING_ASCII(&constant_bin[ 6916 ], 5, 1);
    const_str_plain_bytes = UNSTREAM_STRING_ASCII(&constant_bin[ 86694 ], 5, 1);
    const_str_plain_chown = UNSTREAM_STRING_ASCII(&constant_bin[ 78349 ], 5, 1);
    const_str_plain_close = UNSTREAM_STRING_ASCII(&constant_bin[ 11933 ], 5, 1);
    const_str_plain_debug = UNSTREAM_STRING_ASCII(&constant_bin[ 95597 ], 5, 1);
    const_str_plain_dict_ = UNSTREAM_STRING_ASCII(&constant_bin[ 95602 ], 5, 1);
    const_str_plain_error = UNSTREAM_STRING_ASCII(&constant_bin[ 3280 ], 5, 1);
    const_str_plain_field = UNSTREAM_STRING_ASCII(&constant_bin[ 10370 ], 5, 1);
    const_str_plain_flags = UNSTREAM_STRING_ASCII(&constant_bin[ 5799 ], 5, 1);
    const_str_plain_float = UNSTREAM_STRING_ASCII(&constant_bin[ 59042 ], 5, 1);
    const_str_plain_iface = UNSTREAM_STRING_ASCII(&constant_bin[ 30588 ], 5, 1);
    const_str_plain_items = UNSTREAM_STRING_ASCII(&constant_bin[ 77348 ], 5, 1);
    const_str_plain_klass = UNSTREAM_STRING_ASCII(&constant_bin[ 74473 ], 5, 1);
    const_str_plain_level = UNSTREAM_STRING_ASCII(&constant_bin[ 5543 ], 5, 1);
    const_str_plain_limit = UNSTREAM_STRING_ASCII(&constant_bin[ 76996 ], 5, 1);
    const_str_plain_long_ = UNSTREAM_STRING_ASCII(&constant_bin[ 4601 ], 5, 1);
    const_str_plain_lower = UNSTREAM_STRING_ASCII(&constant_bin[ 62507 ], 5, 1);
    const_str_plain_match = UNSTREAM_STRING_ASCII(&constant_bin[ 307 ], 5, 1);
    const_str_plain_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 31753 ], 5, 1);
    const_str_plain_print = UNSTREAM_STRING_ASCII(&constant_bin[ 65140 ], 5, 1);
    const_str_plain_proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 32173 ], 5, 1);
    const_str_plain_range = UNSTREAM_STRING_ASCII(&constant_bin[ 16887 ], 5, 1);
    const_str_plain_split = UNSTREAM_STRING_ASCII(&constant_bin[ 20700 ], 5, 1);
    const_str_plain_strip = UNSTREAM_STRING_ASCII(&constant_bin[ 70598 ], 5, 1);
    const_str_plain_throw = UNSTREAM_STRING_ASCII(&constant_bin[ 95607 ], 5, 1);
    const_str_plain_tools = UNSTREAM_STRING_ASCII(&constant_bin[ 6723 ], 5, 1);
    const_str_plain_tuple = UNSTREAM_STRING_ASCII(&constant_bin[ 2671 ], 5, 1);
    const_str_plain_type_ = UNSTREAM_STRING_ASCII(&constant_bin[ 4998 ], 5, 1);
    const_str_plain_types = UNSTREAM_STRING_ASCII(&constant_bin[ 3413 ], 5, 1);
    const_str_plain_value = UNSTREAM_STRING_ASCII(&constant_bin[ 41859 ], 5, 1);
    const_str_plain_watch = UNSTREAM_STRING_ASCII(&constant_bin[ 8413 ], 5, 1);
    const_str_angle_lambda = UNSTREAM_STRING_ASCII(&constant_bin[ 24946 ], 8, 0);
    const_str_plain_Double = UNSTREAM_STRING_ASCII(&constant_bin[ 26200 ], 6, 1);
    const_str_plain_GBoxed = UNSTREAM_STRING_ASCII(&constant_bin[ 95612 ], 6, 1);
    const_str_plain_GFlags = UNSTREAM_STRING_ASCII(&constant_bin[ 95618 ], 6, 1);
    const_str_plain_NewtIO = UNSTREAM_STRING_ASCII(&constant_bin[ 9523 ], 6, 1);
    const_str_plain_String = UNSTREAM_STRING_ASCII(&constant_bin[ 2226 ], 6, 1);
    const_str_plain_Struct = UNSTREAM_STRING_ASCII(&constant_bin[ 5202 ], 6, 1);
    const_str_plain_TextIO = UNSTREAM_STRING_ASCII(&constant_bin[ 9456 ], 6, 1);
    const_str_plain_UInt16 = UNSTREAM_STRING_ASCII(&constant_bin[ 26162 ], 6, 1);
    const_str_plain_UInt32 = UNSTREAM_STRING_ASCII(&constant_bin[ 26177 ], 6, 1);
    const_str_plain_UInt64 = UNSTREAM_STRING_ASCII(&constant_bin[ 26192 ], 6, 1);
    const_str_plain__proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 52112 ], 6, 1);
    const_str_plain_append = UNSTREAM_STRING_ASCII(&constant_bin[ 56298 ], 6, 1);
    const_str_plain_create = UNSTREAM_STRING_ASCII(&constant_bin[ 15926 ], 6, 1);
    const_str_plain_decode = UNSTREAM_STRING_ASCII(&constant_bin[ 95624 ], 6, 1);
    const_str_plain_delete = UNSTREAM_STRING_ASCII(&constant_bin[ 69885 ], 6, 1);
    const_str_plain_encode = UNSTREAM_STRING_ASCII(&constant_bin[ 95630 ], 6, 1);
    const_str_plain_extend = UNSTREAM_STRING_ASCII(&constant_bin[ 95636 ], 6, 1);
    const_str_plain_format = UNSTREAM_STRING_ASCII(&constant_bin[ 24331 ], 6, 1);
    const_str_plain_g_type = UNSTREAM_STRING_ASCII(&constant_bin[ 3411 ], 6, 1);
    const_str_plain_getpid = UNSTREAM_STRING_ASCII(&constant_bin[ 95642 ], 6, 1);
    const_str_plain_getter = UNSTREAM_STRING_ASCII(&constant_bin[ 60020 ], 6, 1);
    const_str_plain_getuid = UNSTREAM_STRING_ASCII(&constant_bin[ 95648 ], 6, 1);
    const_str_plain_ignore = UNSTREAM_STRING_ASCII(&constant_bin[ 34242 ], 6, 1);
    const_str_plain_is_py2 = UNSTREAM_STRING_ASCII(&constant_bin[ 892 ], 6, 1);
    const_str_plain_is_py3 = UNSTREAM_STRING_ASCII(&constant_bin[ 2198 ], 6, 1);
    const_str_plain_kwargs = UNSTREAM_STRING_ASCII(&constant_bin[ 70646 ], 6, 1);
    const_str_plain_locals = UNSTREAM_STRING_ASCII(&constant_bin[ 24839 ], 6, 1);
    const_str_plain_member = UNSTREAM_STRING_ASCII(&constant_bin[ 2078 ], 6, 1);
    const_str_plain_method = UNSTREAM_STRING_ASCII(&constant_bin[ 1245 ], 6, 1);
    const_str_plain_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5632 ], 6, 1);
    const_str_plain_object = UNSTREAM_STRING_ASCII(&constant_bin[ 2165 ], 6, 1);
    const_str_plain_origin = UNSTREAM_STRING_ASCII(&constant_bin[ 33214 ], 6, 1);
    const_str_plain_pytype = UNSTREAM_STRING_ASCII(&constant_bin[ 5169 ], 6, 1);
    const_str_plain_reason = UNSTREAM_STRING_ASCII(&constant_bin[ 8552 ], 6, 1);
    const_str_plain_remove = UNSTREAM_STRING_ASCII(&constant_bin[ 32061 ], 6, 1);
    const_str_plain_report = UNSTREAM_STRING_ASCII(&constant_bin[ 8505 ], 6, 1);
    const_str_plain_result = UNSTREAM_STRING_ASCII(&constant_bin[ 67537 ], 6, 1);
    const_str_plain_rsplit = UNSTREAM_STRING_ASCII(&constant_bin[ 20699 ], 6, 1);
    const_str_plain_screen = UNSTREAM_STRING_ASCII(&constant_bin[ 169 ], 6, 1);
    const_str_plain_setter = UNSTREAM_STRING_ASCII(&constant_bin[ 59179 ], 6, 1);
    const_str_plain_socket = UNSTREAM_STRING_ASCII(&constant_bin[ 95654 ], 6, 1);
    const_str_plain_syslog = UNSTREAM_STRING_ASCII(&constant_bin[ 642 ], 6, 1);
    const_str_plain_system = UNSTREAM_STRING_ASCII(&constant_bin[ 1310 ], 6, 1);
    const_str_plain_update = UNSTREAM_STRING_ASCII(&constant_bin[ 73245 ], 6, 1);
    const_tuple_none_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    const_str_angle_genexpr = UNSTREAM_STRING_ASCII(&constant_bin[ 66536 ], 9, 0);
    const_str_plain_AF_UNIX = UNSTREAM_STRING_ASCII(&constant_bin[ 95660 ], 7, 1);
    const_str_plain_Boolean = UNSTREAM_STRING_ASCII(&constant_bin[ 26146 ], 7, 1);
    const_str_plain_GObject = UNSTREAM_STRING_ASCII(&constant_bin[ 6128 ], 7, 1);
    const_str_plain_SHUT_WR = UNSTREAM_STRING_ASCII(&constant_bin[ 95667 ], 7, 1);
    const_str_plain_Unknown = UNSTREAM_STRING_ASCII(&constant_bin[ 8357 ], 7, 1);
    const_str_plain___all__ = UNSTREAM_STRING_ASCII(&constant_bin[ 863 ], 7, 1);
    const_str_plain___cmp__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95674 ], 7, 1);
    const_str_plain___dir__ = UNSTREAM_STRING_ASCII(&constant_bin[ 69123 ], 7, 1);
    const_str_plain___doc__ = UNSTREAM_STRING_ASCII(&constant_bin[ 75141 ], 7, 1);
    const_str_plain___get__ = UNSTREAM_STRING_ASCII(&constant_bin[ 62766 ], 7, 1);
    const_str_plain___new__ = UNSTREAM_STRING_ASCII(&constant_bin[ 29757 ], 7, 1);
    const_str_plain___set__ = UNSTREAM_STRING_ASCII(&constant_bin[ 61729 ], 7, 1);
    const_str_plain___str__ = UNSTREAM_STRING_ASCII(&constant_bin[ 45145 ], 7, 1);
    const_str_plain__compat = UNSTREAM_STRING_ASCII(&constant_bin[ 26496 ], 7, 1);
    const_str_plain__logger = UNSTREAM_STRING_ASCII(&constant_bin[ 1734 ], 7, 1);
    const_str_plain_abspath = UNSTREAM_STRING_ASCII(&constant_bin[ 95681 ], 7, 1);
    const_str_plain_acquire = UNSTREAM_STRING_ASCII(&constant_bin[ 95688 ], 7, 1);
    const_str_plain_compile = UNSTREAM_STRING_ASCII(&constant_bin[ 95695 ], 7, 1);
    const_str_plain_connect = UNSTREAM_STRING_ASCII(&constant_bin[ 1207 ], 7, 1);
    const_str_plain_delattr = UNSTREAM_STRING_ASCII(&constant_bin[ 7781 ], 7, 1);
    const_str_plain_duphash = UNSTREAM_STRING_ASCII(&constant_bin[ 95702 ], 7, 1);
    const_str_plain_getattr = UNSTREAM_STRING_ASCII(&constant_bin[ 7810 ], 7, 1);
    const_str_plain_globals = UNSTREAM_STRING_ASCII(&constant_bin[ 9778 ], 7, 1);
    const_str_plain_gobject = UNSTREAM_STRING_ASCII(&constant_bin[ 3725 ], 7, 1);
    const_str_plain_inspect = UNSTREAM_STRING_ASCII(&constant_bin[ 7570 ], 7, 1);
    const_str_plain_isdigit = UNSTREAM_STRING_ASCII(&constant_bin[ 95709 ], 7, 1);
    const_str_plain_logging = UNSTREAM_STRING_ASCII(&constant_bin[ 1705 ], 7, 1);
    const_str_plain_matches = UNSTREAM_STRING_ASCII(&constant_bin[ 307 ], 7, 1);
    const_str_plain_modules = UNSTREAM_STRING_ASCII(&constant_bin[ 6460 ], 7, 1);
    const_str_plain_pkgutil = UNSTREAM_STRING_ASCII(&constant_bin[ 95716 ], 7, 1);
    const_str_plain_private = UNSTREAM_STRING_ASCII(&constant_bin[ 26884 ], 7, 1);
    const_str_plain_problem = UNSTREAM_STRING_ASCII(&constant_bin[ 8611 ], 7, 1);
    const_str_plain_proxies = UNSTREAM_STRING_ASCII(&constant_bin[ 7340 ], 7, 1);
    const_str_plain_release = UNSTREAM_STRING_ASCII(&constant_bin[ 8757 ], 7, 1);
    const_str_plain_replace = UNSTREAM_STRING_ASCII(&constant_bin[ 70206 ], 7, 1);
    const_str_plain_sendall = UNSTREAM_STRING_ASCII(&constant_bin[ 95723 ], 7, 1);
    const_str_plain_timeout = UNSTREAM_STRING_ASCII(&constant_bin[ 84524 ], 7, 1);
    const_str_plain_unicode = UNSTREAM_STRING_ASCII(&constant_bin[ 2764 ], 7, 1);
    const_str_plain_version = UNSTREAM_STRING_ASCII(&constant_bin[ 3307 ], 7, 1);
    const_str_plain_weakref = UNSTREAM_STRING_ASCII(&constant_bin[ 1763 ], 7, 1);
    const_str_plain_wrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 27441 ], 7, 1);
    const_tuple_false_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_false_tuple, 0, Py_False); Py_INCREF(Py_False);
    const_tuple_int_0_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_0_tuple, 0, const_int_0); Py_INCREF(const_int_0);
    const_str_angle_listcomp = UNSTREAM_STRING_ASCII(&constant_bin[ 95730 ], 10, 0);
    const_str_plain_TYPE_INT = UNSTREAM_STRING_ASCII(&constant_bin[ 3856 ], 8, 1);
    const_str_plain___call__ = UNSTREAM_STRING_ASCII(&constant_bin[ 51098 ], 8, 1);
    const_str_plain___dict__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95740 ], 8, 1);
    const_str_plain___exit__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95748 ], 8, 1);
    const_str_plain___file__ = UNSTREAM_STRING_ASCII(&constant_bin[ 3667 ], 8, 1);
    const_str_plain___info__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95756 ], 8, 1);
    const_str_plain___init__ = UNSTREAM_STRING_ASCII(&constant_bin[ 25753 ], 8, 1);
    const_str_plain___iter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 88625 ], 8, 1);
    const_str_plain___main__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95764 ], 8, 1);
    const_str_plain___name__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95772 ], 8, 1);
    const_str_plain___path__ = UNSTREAM_STRING_ASCII(&constant_bin[ 833 ], 8, 1);
    const_str_plain___repr__ = UNSTREAM_STRING_ASCII(&constant_bin[ 1371 ], 8, 1);
    const_str_plain___spec__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95780 ], 8, 1);
    const_str_plain__probdir = UNSTREAM_STRING_ASCII(&constant_bin[ 95788 ], 8, 1);
    const_str_plain_bus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 1523 ], 8, 1);
    const_str_plain_callable = UNSTREAM_STRING_ASCII(&constant_bin[ 5244 ], 8, 1);
    const_str_plain_callback = UNSTREAM_STRING_ASCII(&constant_bin[ 33847 ], 8, 1);
    const_str_plain_datetime = UNSTREAM_STRING_ASCII(&constant_bin[ 7445 ], 8, 1);
    const_str_plain_del_item = UNSTREAM_STRING_ASCII(&constant_bin[ 79572 ], 8, 1);
    const_str_plain_endswith = UNSTREAM_STRING_ASCII(&constant_bin[ 95796 ], 8, 1);
    const_str_plain_exc_info = UNSTREAM_STRING_ASCII(&constant_bin[ 95804 ], 8, 1);
    const_str_plain_fromlist = UNSTREAM_STRING_ASCII(&constant_bin[ 95812 ], 8, 1);
    const_str_plain_funcName = UNSTREAM_STRING_ASCII(&constant_bin[ 95820 ], 8, 1);
    const_str_plain_get_item = UNSTREAM_STRING_ASCII(&constant_bin[ 79846 ], 8, 1);
    const_str_plain_get_name = UNSTREAM_STRING_ASCII(&constant_bin[ 31744 ], 8, 1);
    const_str_plain_get_size = UNSTREAM_STRING_ASCII(&constant_bin[ 95828 ], 8, 1);
    const_str_plain_importer = UNSTREAM_STRING_ASCII(&constant_bin[ 67691 ], 8, 1);
    const_str_plain_instance = UNSTREAM_STRING_ASCII(&constant_bin[ 7696 ], 8, 1);
    const_str_plain_keywords = UNSTREAM_STRING_ASCII(&constant_bin[ 95836 ], 8, 1);
    const_str_plain_list_all = UNSTREAM_STRING_ASCII(&constant_bin[ 79418 ], 8, 1);
    const_str_plain_mainloop = UNSTREAM_STRING_ASCII(&constant_bin[ 26423 ], 8, 1);
    const_str_plain_override = UNSTREAM_STRING_ASCII(&constant_bin[ 5702 ], 8, 1);
    const_str_plain_property = UNSTREAM_STRING_ASCII(&constant_bin[ 1173 ], 8, 1);
    const_str_plain_set_item = UNSTREAM_STRING_ASCII(&constant_bin[ 79396 ], 8, 1);
    const_str_plain_shutdown = UNSTREAM_STRING_ASCII(&constant_bin[ 95844 ], 8, 1);
    const_str_plain_strftime = UNSTREAM_STRING_ASCII(&constant_bin[ 95852 ], 8, 1);
    const_str_plain_warnings = UNSTREAM_STRING_ASCII(&constant_bin[ 5497 ], 8, 1);
    const_str_angle_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 95860 ], 11, 0);
    const_str_plain_ByteArray = UNSTREAM_STRING_ASCII(&constant_bin[ 26118 ], 9, 1);
    const_str_plain_Interface = UNSTREAM_STRING_ASCII(&constant_bin[ 3129 ], 9, 1);
    const_str_plain_Signature = UNSTREAM_STRING_ASCII(&constant_bin[ 26129 ], 9, 1);
    const_str_plain_SystemBus = UNSTREAM_STRING_ASCII(&constant_bin[ 1017 ], 9, 1);
    const_str_plain_TYPE_CHAR = UNSTREAM_STRING_ASCII(&constant_bin[ 3892 ], 9, 1);
    const_str_plain_TYPE_ENUM = UNSTREAM_STRING_ASCII(&constant_bin[ 4508 ], 9, 1);
    const_str_plain_TYPE_LONG = UNSTREAM_STRING_ASCII(&constant_bin[ 4019 ], 9, 1);
    const_str_plain_TYPE_NONE = UNSTREAM_STRING_ASCII(&constant_bin[ 3825 ], 9, 1);
    const_str_plain_TYPE_STRV = UNSTREAM_STRING_ASCII(&constant_bin[ 4443 ], 9, 1);
    const_str_plain_TYPE_UINT = UNSTREAM_STRING_ASCII(&constant_bin[ 3794 ], 9, 1);
    const_str_plain_VFuncInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5068 ], 9, 1);
    const_str_plain___class__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95871 ], 9, 1);
    const_str_plain___debug__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95880 ], 9, 1);
    const_str_plain___enter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95889 ], 9, 1);
    const_str_plain___gtype__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95898 ], 9, 1);
    const_str_plain___slots__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95907 ], 9, 1);
    const_str_plain_bytearray = UNSTREAM_STRING_ASCII(&constant_bin[ 95916 ], 9, 1);
    const_str_plain_exception = UNSTREAM_STRING_ASCII(&constant_bin[ 802 ], 9, 1);
    const_str_plain_getLogger = UNSTREAM_STRING_ASCII(&constant_bin[ 89310 ], 9, 1);
    const_str_plain_get_proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 95925 ], 9, 1);
    const_str_plain_get_value = UNSTREAM_STRING_ASCII(&constant_bin[ 68843 ], 9, 1);
    const_str_plain_importlib = UNSTREAM_STRING_ASCII(&constant_bin[ 3533 ], 9, 1);
    const_str_plain_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 2120 ], 9, 1);
    const_str_plain_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 62044 ], 9, 1);
    const_str_plain_namespace = UNSTREAM_STRING_ASCII(&constant_bin[ 57362 ], 9, 1);
    const_str_plain_overrides = UNSTREAM_STRING_ASCII(&constant_bin[ 5702 ], 9, 1);
    const_str_plain_signature = UNSTREAM_STRING_ASCII(&constant_bin[ 32816 ], 9, 1);
    const_str_plain_threading = UNSTREAM_STRING_ASCII(&constant_bin[ 2286 ], 9, 1);
    const_str_plain_traceback = UNSTREAM_STRING_ASCII(&constant_bin[ 10213 ], 9, 1);
    const_tuple_str_dot_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_dot_tuple, 0, const_str_dot); Py_INCREF(const_str_dot);
    const_slice_none_none_none = PySlice_New(Py_None, Py_None, Py_None);
    const_str_plain_BUS_SYSTEM = UNSTREAM_STRING_ASCII(&constant_bin[ 985 ], 10, 1);
    const_str_plain_Connection = UNSTREAM_STRING_ASCII(&constant_bin[ 1116 ], 10, 1);
    const_str_plain_Dictionary = UNSTREAM_STRING_ASCII(&constant_bin[ 26231 ], 10, 1);
    const_str_plain_GInterface = UNSTREAM_STRING_ASCII(&constant_bin[ 6261 ], 10, 1);
    const_str_plain_LOCAL_PATH = UNSTREAM_STRING_ASCII(&constant_bin[ 2470 ], 10, 1);
    const_str_plain_ModuleType = UNSTREAM_STRING_ASCII(&constant_bin[ 95934 ], 10, 1);
    const_str_plain_ObjectInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5283 ], 10, 1);
    const_str_plain_ObjectPath = UNSTREAM_STRING_ASCII(&constant_bin[ 26106 ], 10, 1);
    const_str_plain_Repository = UNSTREAM_STRING_ASCII(&constant_bin[ 3374 ], 10, 1);
    const_str_plain_SessionBus = UNSTREAM_STRING_ASCII(&constant_bin[ 953 ], 10, 1);
    const_str_plain_StarterBus = UNSTREAM_STRING_ASCII(&constant_bin[ 1081 ], 10, 1);
    const_str_plain_StructInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5202 ], 10, 1);
    const_str_plain_StructMeta = UNSTREAM_STRING_ASCII(&constant_bin[ 6379 ], 10, 1);
    const_str_plain_TYPE_BOXED = UNSTREAM_STRING_ASCII(&constant_bin[ 4246 ], 10, 1);
    const_str_plain_TYPE_FLAGS = UNSTREAM_STRING_ASCII(&constant_bin[ 4539 ], 10, 1);
    const_str_plain_TYPE_FLOAT = UNSTREAM_STRING_ASCII(&constant_bin[ 4147 ], 10, 1);
    const_str_plain_TYPE_GTYPE = UNSTREAM_STRING_ASCII(&constant_bin[ 4411 ], 10, 1);
    const_str_plain_TYPE_INT64 = UNSTREAM_STRING_ASCII(&constant_bin[ 4082 ], 10, 1);
    const_str_plain_TYPE_PARAM = UNSTREAM_STRING_ASCII(&constant_bin[ 4278 ], 10, 1);
    const_str_plain_TYPE_UCHAR = UNSTREAM_STRING_ASCII(&constant_bin[ 3923 ], 10, 1);
    const_str_plain_TYPE_ULONG = UNSTREAM_STRING_ASCII(&constant_bin[ 4050 ], 10, 1);
    const_str_plain_UTF8String = UNSTREAM_STRING_ASCII(&constant_bin[ 2254 ], 10, 1);
    const_str_plain___cached__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95944 ], 10, 1);
    const_str_plain___import__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9746 ], 10, 1);
    const_str_plain___loader__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95954 ], 10, 1);
    const_str_plain___module__ = UNSTREAM_STRING_ASCII(&constant_bin[ 95964 ], 10, 1);
    const_str_plain__constants = UNSTREAM_STRING_ASCII(&constant_bin[ 59024 ], 10, 1);
    const_str_plain__persisted = UNSTREAM_STRING_ASCII(&constant_bin[ 95974 ], 10, 1);
    const_str_plain_call_async = UNSTREAM_STRING_ASCII(&constant_bin[ 43787 ], 10, 1);
    const_str_plain_exceptions = UNSTREAM_STRING_ASCII(&constant_bin[ 46185 ], 10, 1);
    const_str_plain_executable = UNSTREAM_STRING_ASCII(&constant_bin[ 24307 ], 10, 1);
    const_str_plain_get_g_type = UNSTREAM_STRING_ASCII(&constant_bin[ 95984 ], 10, 1);
    const_str_plain_get_object = UNSTREAM_STRING_ASCII(&constant_bin[ 38382 ], 10, 1);
    const_str_plain_identifier = UNSTREAM_STRING_ASCII(&constant_bin[ 77267 ], 10, 1);
    const_str_plain_introspect = UNSTREAM_STRING_ASCII(&constant_bin[ 3089 ], 10, 1);
    const_str_plain_isinstance = UNSTREAM_STRING_ASCII(&constant_bin[ 7694 ], 10, 1);
    const_str_plain_issubclass = UNSTREAM_STRING_ASCII(&constant_bin[ 95994 ], 10, 1);
    const_str_plain_problemify = UNSTREAM_STRING_ASCII(&constant_bin[ 96004 ], 10, 1);
    const_str_plain_pyanaconda = UNSTREAM_STRING_ASCII(&constant_bin[ 81222 ], 10, 1);
    const_str_plain_repository = UNSTREAM_STRING_ASCII(&constant_bin[ 5441 ], 10, 1);
    const_str_plain_setdefault = UNSTREAM_STRING_ASCII(&constant_bin[ 96014 ], 10, 1);
    const_str_plain_settimeout = UNSTREAM_STRING_ASCII(&constant_bin[ 96024 ], 10, 1);
    const_str_plain_stacklevel = UNSTREAM_STRING_ASCII(&constant_bin[ 5538 ], 10, 1);
    const_str_plain_startswith = UNSTREAM_STRING_ASCII(&constant_bin[ 96034 ], 10, 1);
    const_tuple_type_str_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_str_tuple, 0, (PyObject *)&PyUnicode_Type); Py_INCREF((PyObject *)&PyUnicode_Type);
    const_str_plain_AuthFailure = UNSTREAM_STRING_ASCII(&constant_bin[ 80126 ], 11, 1);
    const_str_plain_BUS_SESSION = UNSTREAM_STRING_ASCII(&constant_bin[ 920 ], 11, 1);
    const_str_plain_BUS_STARTER = UNSTREAM_STRING_ASCII(&constant_bin[ 1048 ], 11, 1);
    const_str_plain_GObjectMeta = UNSTREAM_STRING_ASCII(&constant_bin[ 6128 ], 11, 1);
    const_str_plain_HAVE_POLKIT = UNSTREAM_STRING_ASCII(&constant_bin[ 96044 ], 11, 1);
    const_str_plain_ImportError = UNSTREAM_STRING_ASCII(&constant_bin[ 8440 ], 11, 1);
    const_str_plain_LOCAL_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 2437 ], 11, 1);
    const_str_plain_ProxyObject = UNSTREAM_STRING_ASCII(&constant_bin[ 2731 ], 11, 1);
    const_str_plain_PyGIWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 3634 ], 11, 1);
    const_str_plain_SOCK_STREAM = UNSTREAM_STRING_ASCII(&constant_bin[ 96055 ], 11, 1);
    const_str_plain_TYPE_DOUBLE = UNSTREAM_STRING_ASCII(&constant_bin[ 4179 ], 11, 1);
    const_str_plain_TYPE_OBJECT = UNSTREAM_STRING_ASCII(&constant_bin[ 4310 ], 11, 1);
    const_str_plain_TYPE_STRING = UNSTREAM_STRING_ASCII(&constant_bin[ 4343 ], 11, 1);
    const_str_plain_TYPE_SYSTEM = UNSTREAM_STRING_ASCII(&constant_bin[ 26792 ], 11, 1);
    const_str_plain_TYPE_UINT64 = UNSTREAM_STRING_ASCII(&constant_bin[ 4114 ], 11, 1);
    const_str_plain___getattr__ = UNSTREAM_STRING_ASCII(&constant_bin[ 51731 ], 11, 1);
    const_str_plain___getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 77495 ], 11, 1);
    const_str_plain___package__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96066 ], 11, 1);
    const_str_plain___prepare__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96077 ], 11, 1);
    const_str_plain___version__ = UNSTREAM_STRING_ASCII(&constant_bin[ 3341 ], 11, 1);
    const_str_plain__connection = UNSTREAM_STRING_ASCII(&constant_bin[ 1206 ], 11, 1);
    const_str_plain_basicConfig = UNSTREAM_STRING_ASCII(&constant_bin[ 96088 ], 11, 1);
    const_str_plain_classmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 96099 ], 11, 1);
    const_str_plain_collections = UNSTREAM_STRING_ASCII(&constant_bin[ 96110 ], 11, 1);
    const_str_plain_extend_path = UNSTREAM_STRING_ASCII(&constant_bin[ 96121 ], 11, 1);
    const_str_plain_get_default = UNSTREAM_STRING_ASCII(&constant_bin[ 25484 ], 11, 1);
    const_str_plain_get_methods = UNSTREAM_STRING_ASCII(&constant_bin[ 96132 ], 11, 1);
    const_str_plain_get_version = UNSTREAM_STRING_ASCII(&constant_bin[ 96143 ], 11, 1);
    const_str_plain_method_info = UNSTREAM_STRING_ASCII(&constant_bin[ 96154 ], 11, 1);
    const_str_plain_object_path = UNSTREAM_STRING_ASCII(&constant_bin[ 2165 ], 11, 1);
    const_str_plain_signal_name = UNSTREAM_STRING_ASCII(&constant_bin[ 38990 ], 11, 1);
    const_tuple_int_pos_5_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_5_tuple, 0, const_int_pos_5); Py_INCREF(const_int_pos_5);
    const_tuple_str_empty_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_empty_tuple, 0, const_str_empty); Py_INCREF(const_str_empty);
    const_str_plain_CallableInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5361 ], 12, 1);
    const_str_plain_ErrorMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2609 ], 12, 1);
    const_str_plain_FunctionInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5099 ], 12, 1);
    const_str_plain_TYPE_BOOLEAN = UNSTREAM_STRING_ASCII(&constant_bin[ 3985 ], 12, 1);
    const_str_plain_TYPE_INVALID = UNSTREAM_STRING_ASCII(&constant_bin[ 6685 ], 12, 1);
    const_str_plain_TYPE_POINTER = UNSTREAM_STRING_ASCII(&constant_bin[ 4212 ], 12, 1);
    const_str_plain_TYPE_SESSION = UNSTREAM_STRING_ASCII(&constant_bin[ 2035 ], 12, 1);
    const_str_plain_TYPE_STARTER = UNSTREAM_STRING_ASCII(&constant_bin[ 26811 ], 12, 1);
    const_str_plain_TYPE_VARIANT = UNSTREAM_STRING_ASCII(&constant_bin[ 4474 ], 12, 1);
    const_str_plain___builtins__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96165 ], 12, 1);
    const_str_plain___compiled__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96177 ], 12, 1);
    const_str_plain___qualname__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96189 ], 12, 1);
    const_str_plain_has_location = UNSTREAM_STRING_ASCII(&constant_bin[ 96201 ], 12, 1);
    const_str_plain_problem_data = UNSTREAM_STRING_ASCII(&constant_bin[ 9358 ], 12, 1);
    const_str_plain_staticmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 1239 ], 12, 1);
    const_str_plain_string_types = UNSTREAM_STRING_ASCII(&constant_bin[ 3406 ], 12, 1);
    const_str_plain_threads_init = UNSTREAM_STRING_ASCII(&constant_bin[ 2836 ], 12, 1);
    const_str_plain_utf8_strings = UNSTREAM_STRING_ASCII(&constant_bin[ 38448 ], 12, 1);
    const_str_plain_version_info = UNSTREAM_STRING_ASCII(&constant_bin[ 3307 ], 12, 1);
    const_tuple_str_chr_42_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_chr_42_tuple, 0, const_str_chr_42); Py_INCREF(const_str_chr_42);
    const_tuple_true_false_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_true_false_tuple, 0, Py_True); Py_INCREF(Py_True);
    PyTuple_SET_ITEM(const_tuple_true_false_tuple, 1, Py_False); Py_INCREF(Py_False);
    const_str_plain_BusConnection = UNSTREAM_STRING_ASCII(&constant_bin[ 1113 ], 13, 1);
    const_str_plain_DBusException = UNSTREAM_STRING_ASCII(&constant_bin[ 1832 ], 13, 1);
    const_str_plain_DBusGMainLoop = UNSTREAM_STRING_ASCII(&constant_bin[ 96213 ], 13, 1);
    const_str_plain_InterfaceInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 6226 ], 13, 1);
    const_str_plain_PROBLEM_TYPES = UNSTREAM_STRING_ASCII(&constant_bin[ 96226 ], 13, 1);
    const_str_plain_SignalMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2350 ], 13, 1);
    const_str_plain_TYPE_PYOBJECT = UNSTREAM_STRING_ASCII(&constant_bin[ 4376 ], 13, 1);
    const_str_plain___docformat__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96239 ], 13, 1);
    const_str_plain___metaclass__ = UNSTREAM_STRING_ASCII(&constant_bin[ 62042 ], 13, 1);
    const_str_plain__initializing = UNSTREAM_STRING_ASCII(&constant_bin[ 96252 ], 13, 1);
    const_str_plain_call_blocking = UNSTREAM_STRING_ASCII(&constant_bin[ 45120 ], 13, 1);
    const_str_plain_error_handler = UNSTREAM_STRING_ASCII(&constant_bin[ 45291 ], 13, 1);
    const_str_plain_fromtimestamp = UNSTREAM_STRING_ASCII(&constant_bin[ 96265 ], 13, 1);
    const_str_plain_get_arguments = UNSTREAM_STRING_ASCII(&constant_bin[ 96278 ], 13, 1);
    const_str_plain_get_dbus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 46410 ], 13, 1);
    const_str_plain_get_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 6081 ], 13, 1);
    const_str_plain_get_namespace = UNSTREAM_STRING_ASCII(&constant_bin[ 96291 ], 13, 1);
    const_str_plain_import_module = UNSTREAM_STRING_ASCII(&constant_bin[ 96304 ], 13, 1);
    const_str_plain_named_service = UNSTREAM_STRING_ASCII(&constant_bin[ 32521 ], 13, 1);
    const_str_plain_reply_handler = UNSTREAM_STRING_ASCII(&constant_bin[ 43448 ], 13, 1);
    const_tuple_int_pos_256_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_256_tuple, 0, const_int_pos_256); Py_INCREF(const_int_pos_256);
    const_tuple_str_plain_x_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_x_tuple, 0, const_str_plain_x); Py_INCREF(const_str_plain_x);
    const_tuple_type_object_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type); Py_INCREF((PyObject *)&PyBaseObject_Type);
    const_str_plain_AttributeError = UNSTREAM_STRING_ASCII(&constant_bin[ 7475 ], 14, 1);
    const_str_plain_InvalidProblem = UNSTREAM_STRING_ASCII(&constant_bin[ 79461 ], 14, 1);
    const_str_plain_ProblemWatcher = UNSTREAM_STRING_ASCII(&constant_bin[ 76399 ], 14, 1);
    const_str_plain_TYPE_INTERFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 3856 ], 14, 1);
    const_str_plain___orig_bases__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96317 ], 14, 1);
    const_str_plain__dbus_bindings = UNSTREAM_STRING_ASCII(&constant_bin[ 2793 ], 14, 1);
    const_str_plain_dbus_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 39092 ], 14, 1);
    const_str_plain_is_constructor = UNSTREAM_STRING_ASCII(&constant_bin[ 96331 ], 14, 1);
    const_str_plain_load_overrides = UNSTREAM_STRING_ASCII(&constant_bin[ 5697 ], 14, 1);
    const_slice_int_pos_1_none_none = PySlice_New(const_int_pos_1, Py_None, Py_None);
    const_slice_int_pos_3_none_none = PySlice_New(const_int_pos_3, Py_None, Py_None);
    const_slice_none_int_pos_3_none = PySlice_New(Py_None, const_int_pos_3, Py_None);
    const_str_plain_BUS_DAEMON_NAME = UNSTREAM_STRING_ASCII(&constant_bin[ 1591 ], 15, 1);
    const_str_plain_BUS_DAEMON_PATH = UNSTREAM_STRING_ASCII(&constant_bin[ 1628 ], 15, 1);
    const_str_plain_DynamicImporter = UNSTREAM_STRING_ASCII(&constant_bin[ 6750 ], 15, 1);
    const_str_plain_ValidationError = UNSTREAM_STRING_ASCII(&constant_bin[ 96345 ], 15, 1);
    const_str_plain___annotations__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96360 ], 15, 1);
    const_str_plain___mro_entries__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96375 ], 15, 1);
    const_str_plain_absolute_import = UNSTREAM_STRING_ASCII(&constant_bin[ 96390 ], 15, 1);
    const_str_plain_install_signals = UNSTREAM_STRING_ASCII(&constant_bin[ 96405 ], 15, 1);
    const_str_plain_require_version = UNSTREAM_STRING_ASCII(&constant_bin[ 3471 ], 15, 1);
    const_tuple_str_plain__gi_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain__gi_tuple, 0, const_str_plain__gi); Py_INCREF(const_str_plain__gi);
    const_str_plain_BUS_DAEMON_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 1553 ], 16, 1);
    const_str_plain_ProxyObjectClass = UNSTREAM_STRING_ASCII(&constant_bin[ 96420 ], 16, 1);
    const_str_plain_handler_function = UNSTREAM_STRING_ASCII(&constant_bin[ 38681 ], 16, 1);
    const_str_plain_reStructuredText = UNSTREAM_STRING_ASCII(&constant_bin[ 96436 ], 16, 1);
    const_str_plain_restructuredtext = UNSTREAM_STRING_ASCII(&constant_bin[ 96452 ], 16, 1);
    const_tuple_none_none_none_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 2, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain_self_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    const_tuple_str_plain_void_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_void_tuple, 0, const_str_plain_void); Py_INCREF(const_str_plain_void);
    const_tuple_str_plain_warn_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_warn_tuple, 0, const_str_plain_warn); Py_INCREF(const_str_plain_warn);
    const_tuple_type_Exception_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_Exception_tuple, 0, (PyObject *)PyExc_Exception); Py_INCREF((PyObject *)PyExc_Exception);
    const_str_plain_MethodCallMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2502 ], 17, 1);
    const_str_plain___class_getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96468 ], 17, 1);
    const_str_plain_require_main_loop = UNSTREAM_STRING_ASCII(&constant_bin[ 96485 ], 17, 1);
    const_str_plain_validate_bus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 1514 ], 17, 1);
    const_str_plain_DeprecationWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 1792 ], 18, 1);
    const_str_plain__require_main_loop = UNSTREAM_STRING_ASCII(&constant_bin[ 96484 ], 18, 1);
    const_str_plain_enumerate_versions = UNSTREAM_STRING_ASCII(&constant_bin[ 96502 ], 18, 1);
    const_str_plain_install_properties = UNSTREAM_STRING_ASCII(&constant_bin[ 61428 ], 18, 1);
    const_tuple_str_plain_is_py2_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_is_py2_tuple, 0, const_str_plain_is_py2); Py_INCREF(const_str_plain_is_py2);
    const_str_plain_MethodReturnMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2568 ], 19, 1);
    const_str_plain_NameExistsException = UNSTREAM_STRING_ASCII(&constant_bin[ 26393 ], 19, 1);
    const_str_plain_ValidationException = UNSTREAM_STRING_ASCII(&constant_bin[ 26318 ], 19, 1);
    const_str_plain_activate_name_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 37031 ], 19, 1);
    const_str_plain_add_signal_receiver = UNSTREAM_STRING_ASCII(&constant_bin[ 31772 ], 19, 1);
    const_str_plain_generate_doc_string = UNSTREAM_STRING_ASCII(&constant_bin[ 4951 ], 19, 1);
    const_str_plain_get_problem_watcher = UNSTREAM_STRING_ASCII(&constant_bin[ 79038 ], 19, 1);
    const_str_plain_validate_error_name = UNSTREAM_STRING_ASCII(&constant_bin[ 25956 ], 19, 1);
    const_tuple_str_dot_int_pos_1_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_dot_int_pos_1_tuple, 0, const_str_dot); Py_INCREF(const_str_dot);
    PyTuple_SET_ITEM(const_tuple_str_dot_int_pos_1_tuple, 1, const_int_pos_1); Py_INCREF(const_int_pos_1);
    const_tuple_str_plain_GObject_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_GObject_tuple, 0, const_str_plain_GObject); Py_INCREF(const_str_plain_GObject);
    const_str_plain_INTROSPECTABLE_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 3039 ], 20, 1);
    const_str_plain_get_required_version = UNSTREAM_STRING_ASCII(&constant_bin[ 96520 ], 20, 1);
    const_str_plain_introspection_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5618 ], 20, 1);
    const_str_plain_validate_member_name = UNSTREAM_STRING_ASCII(&constant_bin[ 2069 ], 20, 1);
    const_str_plain_validate_object_path = UNSTREAM_STRING_ASCII(&constant_bin[ 2156 ], 20, 1);
    const_str_plain_DEFAULT_DUMP_LOCATION = UNSTREAM_STRING_ASCII(&constant_bin[ 96540 ], 21, 1);
    const_str_plain_set_sender_name_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 38522 ], 21, 1);
    const_tuple_int_pos_3_int_pos_3_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_pos_3_tuple, 0, const_int_pos_3); Py_INCREF(const_int_pos_3);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_pos_3_tuple, 1, const_int_pos_3); Py_INCREF(const_int_pos_3);
    const_tuple_none_none_none_none_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 2, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 3, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain___class___tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain___class___tuple, 0, const_str_plain___class__); Py_INCREF(const_str_plain___class__);
    const_str_plain_PyGIDeprecationWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 3590 ], 22, 1);
    const_str_plain_UnknownMethodException = UNSTREAM_STRING_ASCII(&constant_bin[ 26369 ], 22, 1);
    const_str_plain__clean_up_signal_match = UNSTREAM_STRING_ASCII(&constant_bin[ 31385 ], 22, 1);
    const_tuple_str_plain_UTF8String_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_UTF8String_tuple, 0, const_str_plain_UTF8String); Py_INCREF(const_str_plain_UTF8String);
    const_str_plain_validate_interface_name = UNSTREAM_STRING_ASCII(&constant_bin[ 2111 ], 23, 1);
    const_tuple_str_plain_PyGIWarning_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_PyGIWarning_tuple, 0, const_str_plain_PyGIWarning); Py_INCREF(const_str_plain_PyGIWarning);
    const_tuple_str_plain_extend_path_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_extend_path_tuple, 0, const_str_plain_extend_path); Py_INCREF(const_str_plain_extend_path);
    const_str_plain_DBUS_START_REPLY_SUCCESS = UNSTREAM_STRING_ASCII(&constant_bin[ 1935 ], 24, 1);
    const_str_plain_get_introspection_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5614 ], 24, 1);
    const_tuple_str_chr_45_str_plain___tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_chr_45_str_plain___tuple, 0, const_str_chr_45); Py_INCREF(const_str_chr_45);
    PyTuple_SET_ITEM(const_tuple_str_chr_45_str_plain___tuple, 1, const_str_plain__); Py_INCREF(const_str_plain__);
    const_str_plain_follow_name_owner_changes = UNSTREAM_STRING_ASCII(&constant_bin[ 32840 ], 25, 1);
    const_tuple_str_plain_BusConnection_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_BusConnection_tuple, 0, const_str_plain_BusConnection); Py_INCREF(const_str_plain_BusConnection);
    const_tuple_str_plain_DBusException_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_DBusException_tuple, 0, const_str_plain_DBusException); Py_INCREF(const_str_plain_DBusException);
    const_str_plain_process_introspection_data = UNSTREAM_STRING_ASCII(&constant_bin[ 3081 ], 26, 1);
    const_str_plain_submodule_search_locations = UNSTREAM_STRING_ASCII(&constant_bin[ 96561 ], 26, 1);
    const_dict_f154c9a58c9419d7e391901d7b7fe49e = _PyDict_NewPresized( 1 );
    PyDict_SetItem(const_dict_f154c9a58c9419d7e391901d7b7fe49e, const_str_plain_stacklevel, const_int_pos_2);
    assert(PyDict_Size(const_dict_f154c9a58c9419d7e391901d7b7fe49e) == 1);
    const_str_plain_IntrospectionParserException = UNSTREAM_STRING_ASCII(&constant_bin[ 1464 ], 28, 1);
    const_str_plain_MissingErrorHandlerException = UNSTREAM_STRING_ASCII(&constant_bin[ 2962 ], 28, 1);
    const_str_plain_MissingReplyHandlerException = UNSTREAM_STRING_ASCII(&constant_bin[ 2912 ], 28, 1);
    const_str_plain_HANDLER_RESULT_NOT_YET_HANDLED = UNSTREAM_STRING_ASCII(&constant_bin[ 2385 ], 30, 1);
    const_tuple_str_plain_named_service_none_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_named_service_none_tuple, 0, const_str_plain_named_service); Py_INCREF(const_str_plain_named_service);
    PyTuple_SET_ITEM(const_tuple_str_plain_named_service_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain_self_str_plain_name_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_name_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_name_tuple, 1, const_str_plain_name); Py_INCREF(const_str_plain_name);
    const_tuple_str_plain_self_str_plain_path_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_path_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_path_tuple, 1, const_str_plain_path); Py_INCREF(const_str_plain_path);
    const_str_plain_DBUS_START_REPLY_ALREADY_RUNNING = UNSTREAM_STRING_ASCII(&constant_bin[ 1981 ], 32, 1);
    const_str_digest_09d63a5a61044765cbef1a09e46446f1 = UNSTREAM_STRING_ASCII(&constant_bin[ 96587 ], 38, 0);
    const_str_digest_0b385b2a67f6700b8faf677cdd479207 = UNSTREAM_STRING_ASCII(&constant_bin[ 42317 ], 15, 0);
    const_str_digest_176045277faffdb215e36349ee6bf75e = UNSTREAM_STRING_ASCII(&constant_bin[ 96625 ], 39, 0);
    const_str_digest_18c67c412066bef703396d613a159b4d = UNSTREAM_STRING_ASCII(&constant_bin[ 96664 ], 114, 0);
    const_str_digest_1b131d6ac44490cf7b663211212d8dfa = UNSTREAM_STRING_ASCII(&constant_bin[ 96778 ], 49, 0);
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING_ASCII(&constant_bin[ 56983 ], 2, 0);
    const_str_digest_286d73d90a388265c9abc0d24ef29c6f = UNSTREAM_STRING_ASCII(&constant_bin[ 30634 ], 29, 0);
    const_str_digest_2dddc6e15ab2dcfb5a2b2205b5654fb4 = UNSTREAM_STRING_ASCII(&constant_bin[ 74941 ], 14, 0);
    const_str_digest_3aa5bee4de9b0149ae46ffed8a38c6b4 = UNSTREAM_STRING_ASCII(&constant_bin[ 26514 ], 12, 0);
    const_str_digest_3cc8fcb05b60f7b9437930cdc441ce30 = UNSTREAM_STRING_ASCII(&constant_bin[ 96827 ], 52, 0);
    const_str_digest_4289e46f026bf0dd92edd4764f9ca580 = UNSTREAM_STRING_ASCII(&constant_bin[ 96879 ], 105, 0);
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING_ASCII(&constant_bin[ 25677 ], 7, 0);
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING_ASCII(&constant_bin[ 96984 ], 15, 0);
    const_str_digest_6090a95f7b926ecd6061b143b7cad52f = UNSTREAM_STRING_ASCII(&constant_bin[ 96999 ], 51, 0);
    const_str_digest_62223e4c0fc7bcb5885146e43f1fb665 = UNSTREAM_STRING_ASCII(&constant_bin[ 29864 ], 10, 0);
    const_str_digest_66f7aeb02c13e91a30a18f0ea911888b = UNSTREAM_STRING_ASCII(&constant_bin[ 57819 ], 13, 0);
    const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb = UNSTREAM_STRING_ASCII(&constant_bin[ 97050 ], 25, 0);
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING_ASCII(&constant_bin[ 97075 ], 46, 0);
    const_str_digest_79ed2cac4e638f0656fd263c1190bdb0 = UNSTREAM_STRING_ASCII(&constant_bin[ 27072 ], 8, 0);
    const_str_digest_8e2db9d493d0360a27a3bf19583a3201 = UNSTREAM_STRING_ASCII(&constant_bin[ 33633 ], 12, 0);
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING_ASCII(&constant_bin[ 97121 ], 46, 0);
    const_str_digest_a70d2bed936523093700e5558854519a = UNSTREAM_STRING_ASCII(&constant_bin[ 97167 ], 25, 0);
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 97192 ], 47, 0);
    const_str_digest_b0cc034d9177fde48a3b44ac122139d9 = UNSTREAM_STRING_ASCII(&constant_bin[ 42298 ], 6, 0);
    const_str_digest_b45a3c6f685a3991de51197626bab5ca = UNSTREAM_STRING_ASCII(&constant_bin[ 41562 ], 13, 0);
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING_ASCII(&constant_bin[ 16026 ], 2, 1);
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING_ASCII(&constant_bin[ 97239 ], 5, 0);
    const_str_digest_d7a2d3682b691f7fb6d75512d991b529 = UNSTREAM_STRING_ASCII(&constant_bin[ 97244 ], 13, 0);
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING_ASCII(&constant_bin[ 11094 ], 2, 0);
    const_str_digest_e48610c30fffad33f2054d9dca0792b3 = UNSTREAM_STRING_ASCII(&constant_bin[ 46180 ], 15, 0);
    const_str_digest_ec911d7d8aa19d9c1e00a67b34952d6e = UNSTREAM_STRING_ASCII(&constant_bin[ 72242 ], 12, 0);
    const_str_digest_f570069e0d46f80dd06443468800a290 = UNSTREAM_STRING_ASCII(&constant_bin[ 24778 ], 4, 0);
    const_str_digest_fcf040720b88d60da4ce975010c44a3a = UNSTREAM_STRING_ASCII(&constant_bin[ 97257 ], 38, 0);
    const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 97295 ], 48, 0);
    const_tuple_str_plain_args_str_plain_kwargs_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_args); Py_INCREF(const_str_plain_args);
    PyTuple_SET_ITEM(const_tuple_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_kwargs); Py_INCREF(const_str_plain_kwargs);
    const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 0, const_str_plain_Bus); Py_INCREF(const_str_plain_Bus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 1, const_str_plain_SystemBus); Py_INCREF(const_str_plain_SystemBus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 2, const_str_plain_SessionBus); Py_INCREF(const_str_plain_SessionBus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 3, const_str_plain_StarterBus); Py_INCREF(const_str_plain_StarterBus);
    const_tuple_str_plain_PyGIDeprecationWarning_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_PyGIDeprecationWarning_tuple, 0, const_str_plain_PyGIDeprecationWarning); Py_INCREF(const_str_plain_PyGIDeprecationWarning);
    const_tuple_str_plain_self_str_plain_bus_name_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_bus_name_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_bus_name_tuple, 1, const_str_plain_bus_name); Py_INCREF(const_str_plain_bus_name);
    const_tuple_str_plain_self_str_plain_instance_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_tuple, 1, const_str_plain_instance); Py_INCREF(const_str_plain_instance);
    const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple, 0, const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb); Py_INCREF(const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb);
    const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple, 0, const_str_digest_c075052d723d6707083e869a0e3659bb); Py_INCREF(const_str_digest_c075052d723d6707083e869a0e3659bb);
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type); Py_INCREF((PyObject *)&PyFunction_Type);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type); Py_INCREF((PyObject *)&PyCFunction_Type);
    const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 1, const_str_plain_instance); Py_INCREF(const_str_plain_instance);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 2, const_str_plain_owner); Py_INCREF(const_str_plain_owner);

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );

#ifndef _NUITKA_STANDALONE
    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );


#if PYTHON_VERSION >= 300
    /* Set the "sys.base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.exec_base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

#endif
#endif
#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(9));

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, Nuitka_String_FromString("candidate"));

    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants(void) {

}
#endif

void createGlobalConstants(void) {
    if (_sentinel_value == NULL) {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr(NULL, NULL);
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New((void *)27, "sentinel", NULL);
#endif
        assert(_sentinel_value);

        _createGlobalConstants();
    }
}
