
#include "nuitka/prelude.h"
#include "structseq.h"

// Sentinel PyObject to be used for all our call iterator endings. It will
// become a PyCObject pointing to NULL. It's address is unique, and that's
// enough for us to use it as sentinel value.
PyObject *_sentinel_value = NULL;

PyObject *Nuitka_dunder_compiled_value = NULL;

// We need to make sure this is local to the package, or else it will
// be taken from any external linkage.
#if defined(_NUITKA_MODULE) && !defined(_NUITKA_CONSTANTS_FROM_RESOURCE) && !defined(__cplusplus)
const unsigned char constant_bin[0];
#endif

PyObject *const_int_0;
PyObject *const_str_dot;
PyObject *const_float_0_0;
PyObject *const_float_1_0;
PyObject *const_int_neg_1;
PyObject *const_int_pos_1;
PyObject *const_int_pos_2;
PyObject *const_int_pos_3;
PyObject *const_int_pos_4;
PyObject *const_int_pos_5;
PyObject *const_int_pos_7;
PyObject *const_str_empty;
PyObject *const_dict_empty;
PyObject *const_str_chr_42;
PyObject *const_str_chr_45;
PyObject *const_str_chr_58;
PyObject *const_str_chr_61;
PyObject *const_bytes_empty;
PyObject *const_int_pos_256;
PyObject *const_str_newline;
PyObject *const_str_plain__;
PyObject *const_str_plain_e;
PyObject *const_str_plain_h;
PyObject *const_str_plain_i;
PyObject *const_str_plain_l;
PyObject *const_str_plain_m;
PyObject *const_str_plain_p;
PyObject *const_str_plain_r;
PyObject *const_str_plain_s;
PyObject *const_str_plain_t;
PyObject *const_str_plain_u;
PyObject *const_str_plain_x;
PyObject *const_tuple_empty;
PyObject *const_str_plain_cb;
PyObject *const_str_plain_ex;
PyObject *const_str_plain_gi;
PyObject *const_str_plain_id;
PyObject *const_str_plain_io;
PyObject *const_str_plain_os;
PyObject *const_str_plain_rb;
PyObject *const_str_plain_tb;
PyObject *const_str_plain_Bus;
PyObject *const_str_plain_END;
PyObject *const_str_plain_RED;
PyObject *const_str_plain__gi;
PyObject *const_str_plain_add;
PyObject *const_str_plain_ans;
PyObject *const_str_plain_arg;
PyObject *const_str_plain_buf;
PyObject *const_str_plain_bus;
PyObject *const_str_plain_cls;
PyObject *const_str_plain_do_;
PyObject *const_str_plain_doc;
PyObject *const_str_plain_end;
PyObject *const_str_plain_exc;
PyObject *const_str_plain_fun;
PyObject *const_str_plain_get;
PyObject *const_str_plain_gid;
PyObject *const_str_plain_int;
PyObject *const_str_plain_key;
PyObject *const_str_plain_len;
PyObject *const_str_plain_map;
PyObject *const_str_plain_msg;
PyObject *const_str_plain_new;
PyObject *const_str_plain_pg1;
PyObject *const_str_plain_pg2;
PyObject *const_str_plain_pg3;
PyObject *const_str_plain_pg4;
PyObject *const_str_plain_pg5;
PyObject *const_str_plain_pop;
PyObject *const_str_plain_ret;
PyObject *const_str_plain_run;
PyObject *const_str_plain_str;
PyObject *const_str_plain_sum;
PyObject *const_str_plain_sys;
PyObject *const_str_plain_typ;
PyObject *const_str_plain_uid;
PyObject *const_str_plain_use;
PyObject *const_str_plain_val;
PyObject *const_str_plain_zip;
PyObject *const_str_plain_BOLD;
PyObject *const_str_plain_Byte;
PyObject *const_str_plain_args;
PyObject *const_str_plain_argv;
PyObject *const_str_plain_attr;
PyObject *const_str_plain_auth;
PyObject *const_str_plain_bool;
PyObject *const_str_plain_conn;
PyObject *const_str_plain_copy;
PyObject *const_str_plain_data;
PyObject *const_str_plain_dbus;
PyObject *const_str_plain_ddir;
PyObject *const_str_plain_dict;
PyObject *const_str_plain_emit;
PyObject *const_str_plain_exit;
PyObject *const_str_plain_file;
PyObject *const_str_plain_func;
PyObject *const_str_plain_glib;
PyObject *const_str_plain_help;
PyObject *const_str_plain_info;
PyObject *const_str_plain_is_a;
PyObject *const_str_plain_iter;
PyObject *const_str_plain_join;
PyObject *const_str_plain_keys;
PyObject *const_str_plain_list;
PyObject *const_str_plain_look;
PyObject *const_str_plain_name;
PyObject *const_str_plain_open;
PyObject *const_str_plain_path;
PyObject *const_str_plain_prob;
PyObject *const_str_plain_read;
PyObject *const_str_plain_recv;
PyObject *const_str_plain_repr;
PyObject *const_str_plain_rule;
PyObject *const_str_plain_self;
PyObject *const_str_plain_send;
PyObject *const_str_plain_site;
PyObject *const_str_plain_time;
PyObject *const_str_plain_type;
PyObject *const_str_plain_uuid;
PyObject *const_str_plain_void;
PyObject *const_str_plain_warn;
PyObject *const_float_minus_0_0;
PyObject *const_float_minus_1_0;
PyObject *const_str_plain_Array;
PyObject *const_str_plain_ERROR;
PyObject *const_str_plain_False;
PyObject *const_str_plain_GEnum;
PyObject *const_str_plain_GTKIO;
PyObject *const_str_plain_GType;
PyObject *const_str_plain_Int16;
PyObject *const_str_plain_Int32;
PyObject *const_str_plain_Int64;
PyObject *const_str_plain_bases;
PyObject *const_str_plain_bytes;
PyObject *const_str_plain_chown;
PyObject *const_str_plain_clear;
PyObject *const_str_plain_close;
PyObject *const_str_plain_color;
PyObject *const_str_plain_debug;
PyObject *const_str_plain_dict_;
PyObject *const_str_plain_error;
PyObject *const_str_plain_field;
PyObject *const_str_plain_flags;
PyObject *const_str_plain_float;
PyObject *const_str_plain_iface;
PyObject *const_str_plain_input;
PyObject *const_str_plain_items;
PyObject *const_str_plain_klass;
PyObject *const_str_plain_level;
PyObject *const_str_plain_limit;
PyObject *const_str_plain_long_;
PyObject *const_str_plain_lower;
PyObject *const_str_plain_match;
PyObject *const_str_plain_owner;
PyObject *const_str_plain_print;
PyObject *const_str_plain_proxy;
PyObject *const_str_plain_range;
PyObject *const_str_plain_split;
PyObject *const_str_plain_strip;
PyObject *const_str_plain_throw;
PyObject *const_str_plain_tools;
PyObject *const_str_plain_tuple;
PyObject *const_str_plain_type_;
PyObject *const_str_plain_types;
PyObject *const_str_plain_value;
PyObject *const_str_plain_watch;
PyObject *const_str_angle_lambda;
PyObject *const_str_plain_Double;
PyObject *const_str_plain_GBoxed;
PyObject *const_str_plain_GFlags;
PyObject *const_str_plain_NewtIO;
PyObject *const_str_plain_PURPLE;
PyObject *const_str_plain_String;
PyObject *const_str_plain_Struct;
PyObject *const_str_plain_TextIO;
PyObject *const_str_plain_UInt16;
PyObject *const_str_plain_UInt32;
PyObject *const_str_plain_UInt64;
PyObject *const_str_plain__proxy;
PyObject *const_str_plain_append;
PyObject *const_str_plain_create;
PyObject *const_str_plain_decode;
PyObject *const_str_plain_delete;
PyObject *const_str_plain_encode;
PyObject *const_str_plain_extend;
PyObject *const_str_plain_format;
PyObject *const_str_plain_g_type;
PyObject *const_str_plain_getpid;
PyObject *const_str_plain_getter;
PyObject *const_str_plain_getuid;
PyObject *const_str_plain_ignore;
PyObject *const_str_plain_is_py2;
PyObject *const_str_plain_is_py3;
PyObject *const_str_plain_kwargs;
PyObject *const_str_plain_locals;
PyObject *const_str_plain_member;
PyObject *const_str_plain_method;
PyObject *const_str_plain_module;
PyObject *const_str_plain_object;
PyObject *const_str_plain_origin;
PyObject *const_str_plain_pytype;
PyObject *const_str_plain_reason;
PyObject *const_str_plain_remove;
PyObject *const_str_plain_report;
PyObject *const_str_plain_result;
PyObject *const_str_plain_rsplit;
PyObject *const_str_plain_screen;
PyObject *const_str_plain_setter;
PyObject *const_str_plain_socket;
PyObject *const_str_plain_syslog;
PyObject *const_str_plain_system;
PyObject *const_str_plain_update;
PyObject *const_tuple_none_tuple;
PyObject *const_str_angle_genexpr;
PyObject *const_str_plain_AF_UNIX;
PyObject *const_str_plain_Boolean;
PyObject *const_str_plain_GObject;
PyObject *const_str_plain_SHUT_WR;
PyObject *const_str_plain_Unknown;
PyObject *const_str_plain___all__;
PyObject *const_str_plain___cmp__;
PyObject *const_str_plain___dir__;
PyObject *const_str_plain___doc__;
PyObject *const_str_plain___get__;
PyObject *const_str_plain___new__;
PyObject *const_str_plain___set__;
PyObject *const_str_plain___str__;
PyObject *const_str_plain__compat;
PyObject *const_str_plain__logger;
PyObject *const_str_plain_abspath;
PyObject *const_str_plain_acquire;
PyObject *const_str_plain_aliases;
PyObject *const_str_plain_compile;
PyObject *const_str_plain_connect;
PyObject *const_str_plain_delattr;
PyObject *const_str_plain_duphash;
PyObject *const_str_plain_examine;
PyObject *const_str_plain_getattr;
PyObject *const_str_plain_globals;
PyObject *const_str_plain_gobject;
PyObject *const_str_plain_inspect;
PyObject *const_str_plain_isdigit;
PyObject *const_str_plain_logging;
PyObject *const_str_plain_matches;
PyObject *const_str_plain_modules;
PyObject *const_str_plain_pkgutil;
PyObject *const_str_plain_private;
PyObject *const_str_plain_problem;
PyObject *const_str_plain_proxies;
PyObject *const_str_plain_release;
PyObject *const_str_plain_replace;
PyObject *const_str_plain_sendall;
PyObject *const_str_plain_timeout;
PyObject *const_str_plain_unicode;
PyObject *const_str_plain_version;
PyObject *const_str_plain_weakref;
PyObject *const_str_plain_wrapper;
PyObject *const_tuple_false_tuple;
PyObject *const_tuple_int_0_tuple;
PyObject *const_str_angle_listcomp;
PyObject *const_str_plain_TYPE_INT;
PyObject *const_str_plain___call__;
PyObject *const_str_plain___dict__;
PyObject *const_str_plain___exit__;
PyObject *const_str_plain___file__;
PyObject *const_str_plain___info__;
PyObject *const_str_plain___init__;
PyObject *const_str_plain___iter__;
PyObject *const_str_plain___main__;
PyObject *const_str_plain___name__;
PyObject *const_str_plain___path__;
PyObject *const_str_plain___repr__;
PyObject *const_str_plain___spec__;
PyObject *const_str_plain__probdir;
PyObject *const_str_plain_bus_name;
PyObject *const_str_plain_callable;
PyObject *const_str_plain_callback;
PyObject *const_str_plain_commands;
PyObject *const_str_plain_datetime;
PyObject *const_str_plain_del_item;
PyObject *const_str_plain_endswith;
PyObject *const_str_plain_exc_info;
PyObject *const_str_plain_fromlist;
PyObject *const_str_plain_funcName;
PyObject *const_str_plain_get_item;
PyObject *const_str_plain_get_name;
PyObject *const_str_plain_get_size;
PyObject *const_str_plain_importer;
PyObject *const_str_plain_instance;
PyObject *const_str_plain_keywords;
PyObject *const_str_plain_list_all;
PyObject *const_str_plain_mainloop;
PyObject *const_str_plain_override;
PyObject *const_str_plain_property;
PyObject *const_str_plain_set_item;
PyObject *const_str_plain_shutdown;
PyObject *const_str_plain_strftime;
PyObject *const_str_plain_warnings;
PyObject *const_str_angle_metaclass;
PyObject *const_str_plain_ByteArray;
PyObject *const_str_plain_Interface;
PyObject *const_str_plain_Signature;
PyObject *const_str_plain_SystemBus;
PyObject *const_str_plain_TYPE_CHAR;
PyObject *const_str_plain_TYPE_ENUM;
PyObject *const_str_plain_TYPE_LONG;
PyObject *const_str_plain_TYPE_NONE;
PyObject *const_str_plain_TYPE_STRV;
PyObject *const_str_plain_TYPE_UINT;
PyObject *const_str_plain_VFuncInfo;
PyObject *const_str_plain___class__;
PyObject *const_str_plain___debug__;
PyObject *const_str_plain___enter__;
PyObject *const_str_plain___gtype__;
PyObject *const_str_plain___slots__;
PyObject *const_str_plain_burnedout;
PyObject *const_str_plain_bytearray;
PyObject *const_str_plain_exception;
PyObject *const_str_plain_getLogger;
PyObject *const_str_plain_get_proxy;
PyObject *const_str_plain_get_value;
PyObject *const_str_plain_importlib;
PyObject *const_str_plain_interface;
PyObject *const_str_plain_inventory;
PyObject *const_str_plain_metaclass;
PyObject *const_str_plain_namespace;
PyObject *const_str_plain_overrides;
PyObject *const_str_plain_signature;
PyObject *const_str_plain_threading;
PyObject *const_str_plain_traceback;
PyObject *const_tuple_str_dot_tuple;
PyObject *const_slice_none_none_none;
PyObject *const_str_plain_BUS_SYSTEM;
PyObject *const_str_plain_Connection;
PyObject *const_str_plain_Dictionary;
PyObject *const_str_plain_GInterface;
PyObject *const_str_plain_LOCAL_PATH;
PyObject *const_str_plain_ModuleType;
PyObject *const_str_plain_ObjectInfo;
PyObject *const_str_plain_ObjectPath;
PyObject *const_str_plain_Repository;
PyObject *const_str_plain_SessionBus;
PyObject *const_str_plain_StarterBus;
PyObject *const_str_plain_StructInfo;
PyObject *const_str_plain_StructMeta;
PyObject *const_str_plain_TYPE_BOXED;
PyObject *const_str_plain_TYPE_FLAGS;
PyObject *const_str_plain_TYPE_FLOAT;
PyObject *const_str_plain_TYPE_GTYPE;
PyObject *const_str_plain_TYPE_INT64;
PyObject *const_str_plain_TYPE_PARAM;
PyObject *const_str_plain_TYPE_UCHAR;
PyObject *const_str_plain_TYPE_ULONG;
PyObject *const_str_plain_UTF8String;
PyObject *const_str_plain___cached__;
PyObject *const_str_plain___import__;
PyObject *const_str_plain___loader__;
PyObject *const_str_plain___module__;
PyObject *const_str_plain__constants;
PyObject *const_str_plain__persisted;
PyObject *const_str_plain_call_async;
PyObject *const_str_plain_exceptions;
PyObject *const_str_plain_executable;
PyObject *const_str_plain_get_g_type;
PyObject *const_str_plain_get_object;
PyObject *const_str_plain_identifier;
PyObject *const_str_plain_introspect;
PyObject *const_str_plain_isinstance;
PyObject *const_str_plain_issubclass;
PyObject *const_str_plain_pressenter;
PyObject *const_str_plain_problemify;
PyObject *const_str_plain_pyanaconda;
PyObject *const_str_plain_repository;
PyObject *const_str_plain_setdefault;
PyObject *const_str_plain_settimeout;
PyObject *const_str_plain_stacklevel;
PyObject *const_str_plain_startswith;
PyObject *const_tuple_type_str_tuple;
PyObject *const_str_plain_AuthFailure;
PyObject *const_str_plain_BUS_SESSION;
PyObject *const_str_plain_BUS_STARTER;
PyObject *const_str_plain_GObjectMeta;
PyObject *const_str_plain_HAVE_POLKIT;
PyObject *const_str_plain_ImportError;
PyObject *const_str_plain_LOCAL_IFACE;
PyObject *const_str_plain_ProxyObject;
PyObject *const_str_plain_PyGIWarning;
PyObject *const_str_plain_SOCK_STREAM;
PyObject *const_str_plain_TYPE_DOUBLE;
PyObject *const_str_plain_TYPE_OBJECT;
PyObject *const_str_plain_TYPE_STRING;
PyObject *const_str_plain_TYPE_SYSTEM;
PyObject *const_str_plain_TYPE_UINT64;
PyObject *const_str_plain___getattr__;
PyObject *const_str_plain___getitem__;
PyObject *const_str_plain___package__;
PyObject *const_str_plain___prepare__;
PyObject *const_str_plain___version__;
PyObject *const_str_plain__connection;
PyObject *const_str_plain_basicConfig;
PyObject *const_str_plain_classmethod;
PyObject *const_str_plain_collections;
PyObject *const_str_plain_extend_path;
PyObject *const_str_plain_get_default;
PyObject *const_str_plain_get_methods;
PyObject *const_str_plain_get_version;
PyObject *const_str_plain_method_info;
PyObject *const_str_plain_object_path;
PyObject *const_str_plain_signal_name;
PyObject *const_tuple_int_pos_5_tuple;
PyObject *const_tuple_str_empty_tuple;
PyObject *const_str_plain_CallableInfo;
PyObject *const_str_plain_ErrorMessage;
PyObject *const_str_plain_FunctionInfo;
PyObject *const_str_plain_TYPE_BOOLEAN;
PyObject *const_str_plain_TYPE_INVALID;
PyObject *const_str_plain_TYPE_POINTER;
PyObject *const_str_plain_TYPE_SESSION;
PyObject *const_str_plain_TYPE_STARTER;
PyObject *const_str_plain_TYPE_VARIANT;
PyObject *const_str_plain___builtins__;
PyObject *const_str_plain___compiled__;
PyObject *const_str_plain___qualname__;
PyObject *const_str_plain_has_location;
PyObject *const_str_plain_help_command;
PyObject *const_str_plain_outofmatches;
PyObject *const_str_plain_problem_data;
PyObject *const_str_plain_staticmethod;
PyObject *const_str_plain_string_types;
PyObject *const_str_plain_threads_init;
PyObject *const_str_plain_utf8_strings;
PyObject *const_str_plain_version_info;
PyObject *const_tuple_str_chr_42_tuple;
PyObject *const_tuple_true_false_tuple;
PyObject *const_str_plain_BusConnection;
PyObject *const_str_plain_DBusException;
PyObject *const_str_plain_DBusGMainLoop;
PyObject *const_str_plain_InterfaceInfo;
PyObject *const_str_plain_PROBLEM_TYPES;
PyObject *const_str_plain_SignalMessage;
PyObject *const_str_plain_TYPE_PYOBJECT;
PyObject *const_str_plain___docformat__;
PyObject *const_str_plain___metaclass__;
PyObject *const_str_plain__initializing;
PyObject *const_str_plain_call_blocking;
PyObject *const_str_plain_error_handler;
PyObject *const_str_plain_fromtimestamp;
PyObject *const_str_plain_get_arguments;
PyObject *const_str_plain_get_dbus_name;
PyObject *const_str_plain_get_interface;
PyObject *const_str_plain_get_namespace;
PyObject *const_str_plain_import_module;
PyObject *const_str_plain_named_service;
PyObject *const_str_plain_reply_handler;
PyObject *const_tuple_int_pos_256_tuple;
PyObject *const_tuple_str_plain_x_tuple;
PyObject *const_tuple_type_object_tuple;
PyObject *const_str_plain_AttributeError;
PyObject *const_str_plain_InvalidProblem;
PyObject *const_str_plain_ProblemWatcher;
PyObject *const_str_plain_TYPE_INTERFACE;
PyObject *const_str_plain___orig_bases__;
PyObject *const_str_plain__dbus_bindings;
PyObject *const_str_plain_dbus_interface;
PyObject *const_str_plain_is_constructor;
PyObject *const_str_plain_load_overrides;
PyObject *const_slice_int_pos_1_none_none;
PyObject *const_slice_int_pos_3_none_none;
PyObject *const_slice_none_int_pos_3_none;
PyObject *const_str_plain_BUS_DAEMON_NAME;
PyObject *const_str_plain_BUS_DAEMON_PATH;
PyObject *const_str_plain_DynamicImporter;
PyObject *const_str_plain_ValidationError;
PyObject *const_str_plain___annotations__;
PyObject *const_str_plain___mro_entries__;
PyObject *const_str_plain_absolute_import;
PyObject *const_str_plain_install_signals;
PyObject *const_str_plain_require_version;
PyObject *const_tuple_str_plain__gi_tuple;
PyObject *const_str_plain_BUS_DAEMON_IFACE;
PyObject *const_str_plain_ProxyObjectClass;
PyObject *const_str_plain_handler_function;
PyObject *const_str_plain_reStructuredText;
PyObject *const_str_plain_restructuredtext;
PyObject *const_tuple_none_none_none_tuple;
PyObject *const_tuple_str_plain_self_tuple;
PyObject *const_tuple_str_plain_void_tuple;
PyObject *const_tuple_str_plain_warn_tuple;
PyObject *const_tuple_type_Exception_tuple;
PyObject *const_str_plain_MethodCallMessage;
PyObject *const_str_plain___class_getitem__;
PyObject *const_str_plain_inventory_command;
PyObject *const_str_plain_require_main_loop;
PyObject *const_str_plain_validate_bus_name;
PyObject *const_tuple_str_plain_clear_tuple;
PyObject *const_str_plain_DeprecationWarning;
PyObject *const_str_plain__require_main_loop;
PyObject *const_str_plain_enumerate_versions;
PyObject *const_str_plain_install_properties;
PyObject *const_tuple_str_plain_is_py2_tuple;
PyObject *const_str_plain_MethodReturnMessage;
PyObject *const_str_plain_NameExistsException;
PyObject *const_str_plain_ValidationException;
PyObject *const_str_plain_activate_name_owner;
PyObject *const_str_plain_add_signal_receiver;
PyObject *const_str_plain_generate_doc_string;
PyObject *const_str_plain_get_problem_watcher;
PyObject *const_str_plain_validate_error_name;
PyObject *const_tuple_str_dot_int_pos_1_tuple;
PyObject *const_tuple_str_plain_GObject_tuple;
PyObject *const_str_plain_INTROSPECTABLE_IFACE;
PyObject *const_str_plain_get_required_version;
PyObject *const_str_plain_introspection_module;
PyObject *const_str_plain_validate_member_name;
PyObject *const_str_plain_validate_object_path;
PyObject *const_str_plain_DEFAULT_DUMP_LOCATION;
PyObject *const_str_plain_set_sender_name_owner;
PyObject *const_tuple_int_pos_3_int_pos_3_tuple;
PyObject *const_tuple_none_none_none_none_tuple;
PyObject *const_tuple_str_plain___class___tuple;
PyObject *const_str_plain_PyGIDeprecationWarning;
PyObject *const_str_plain_UnknownMethodException;
PyObject *const_str_plain__clean_up_signal_match;
PyObject *const_tuple_str_plain_UTF8String_tuple;
PyObject *const_tuple_str_plain_pressenter_tuple;
PyObject *const_str_plain_validate_interface_name;
PyObject *const_tuple_str_plain_PyGIWarning_tuple;
PyObject *const_tuple_str_plain_extend_path_tuple;
PyObject *const_str_plain_DBUS_START_REPLY_SUCCESS;
PyObject *const_str_plain_get_introspection_module;
PyObject *const_tuple_str_chr_45_str_plain___tuple;
PyObject *const_str_plain_follow_name_owner_changes;
PyObject *const_tuple_str_plain_BusConnection_tuple;
PyObject *const_tuple_str_plain_DBusException_tuple;
PyObject *const_str_plain_process_introspection_data;
PyObject *const_str_plain_submodule_search_locations;
PyObject *const_dict_f154c9a58c9419d7e391901d7b7fe49e;
PyObject *const_str_plain_IntrospectionParserException;
PyObject *const_str_plain_MissingErrorHandlerException;
PyObject *const_str_plain_MissingReplyHandlerException;
PyObject *const_str_plain_HANDLER_RESULT_NOT_YET_HANDLED;
PyObject *const_tuple_str_plain_named_service_none_tuple;
PyObject *const_tuple_str_plain_self_str_plain_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_path_tuple;
PyObject *const_str_plain_DBUS_START_REPLY_ALREADY_RUNNING;
PyObject *const_str_digest_09d63a5a61044765cbef1a09e46446f1;
PyObject *const_str_digest_0b385b2a67f6700b8faf677cdd479207;
PyObject *const_str_digest_176045277faffdb215e36349ee6bf75e;
PyObject *const_str_digest_18c67c412066bef703396d613a159b4d;
PyObject *const_str_digest_1b131d6ac44490cf7b663211212d8dfa;
PyObject *const_str_digest_25731c733fd74e8333aa29126ce85686;
PyObject *const_str_digest_286d73d90a388265c9abc0d24ef29c6f;
PyObject *const_str_digest_2dddc6e15ab2dcfb5a2b2205b5654fb4;
PyObject *const_str_digest_31642840c544e46ac43bf70ce88dbf23;
PyObject *const_str_digest_3501979af1b70861f5e9d6a0f04129bf;
PyObject *const_str_digest_3aa5bee4de9b0149ae46ffed8a38c6b4;
PyObject *const_str_digest_3cc8fcb05b60f7b9437930cdc441ce30;
PyObject *const_str_digest_4289e46f026bf0dd92edd4764f9ca580;
PyObject *const_str_digest_45e4dde2057b0bf276d6a84f4c917d27;
PyObject *const_str_digest_58961c73026e70b23b08cf381b49e04e;
PyObject *const_str_digest_6090a95f7b926ecd6061b143b7cad52f;
PyObject *const_str_digest_62223e4c0fc7bcb5885146e43f1fb665;
PyObject *const_str_digest_66f7aeb02c13e91a30a18f0ea911888b;
PyObject *const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb;
PyObject *const_str_digest_75fd71b1edada749c2ef7ac810062295;
PyObject *const_str_digest_79ed2cac4e638f0656fd263c1190bdb0;
PyObject *const_str_digest_8e2db9d493d0360a27a3bf19583a3201;
PyObject *const_str_digest_9816e8d1552296af90d250823c964059;
PyObject *const_str_digest_a70d2bed936523093700e5558854519a;
PyObject *const_str_digest_adc474dd61fbd736d69c1bac5d9712e0;
PyObject *const_str_digest_b0cc034d9177fde48a3b44ac122139d9;
PyObject *const_str_digest_b45a3c6f685a3991de51197626bab5ca;
PyObject *const_str_digest_b9c4baf879ebd882d40843df3a4dead7;
PyObject *const_str_digest_c075052d723d6707083e869a0e3659bb;
PyObject *const_str_digest_d7a2d3682b691f7fb6d75512d991b529;
PyObject *const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77;
PyObject *const_str_digest_e48610c30fffad33f2054d9dca0792b3;
PyObject *const_str_digest_ec911d7d8aa19d9c1e00a67b34952d6e;
PyObject *const_str_digest_f570069e0d46f80dd06443468800a290;
PyObject *const_str_digest_fcf040720b88d60da4ce975010c44a3a;
PyObject *const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0;
PyObject *const_tuple_str_plain_args_str_plain_kwargs_tuple;
PyObject *const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple;
PyObject *const_tuple_str_plain_PyGIDeprecationWarning_tuple;
PyObject *const_tuple_str_plain_self_str_plain_bus_name_tuple;
PyObject *const_tuple_str_plain_self_str_plain_instance_tuple;
PyObject *const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple;
PyObject *const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple;
PyObject *const_tuple_anon_function_anon_builtin_function_or_method_tuple;
PyObject *const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple;

static void _createGlobalConstants(void) {
    NUITKA_MAY_BE_UNUSED PyObject *exception_type, *exception_value;
    NUITKA_MAY_BE_UNUSED PyTracebackObject *exception_tb;

#ifdef _MSC_VER
    // Prevent unused warnings in case of simple programs, the attribute
    // NUITKA_MAY_BE_UNUSED doesn't work for MSVC.
    (void *)exception_type; (void *)exception_value; (void *)exception_tb;
#endif

    const_int_0 = PyLong_FromUnsignedLong(0ul);
    const_str_dot = UNSTREAM_STRING_ASCII(&constant_bin[ 11113 ], 1, 0);
    const_float_0_0 = UNSTREAM_FLOAT(&constant_bin[ 96478 ]);
    const_float_1_0 = UNSTREAM_FLOAT(&constant_bin[ 96486 ]);
    const_int_neg_1 = PyLong_FromLong(-1l);
    const_int_pos_1 = PyLong_FromUnsignedLong(1ul);
    const_int_pos_2 = PyLong_FromUnsignedLong(2ul);
    const_int_pos_3 = PyLong_FromUnsignedLong(3ul);
    const_int_pos_4 = PyLong_FromUnsignedLong(4ul);
    const_int_pos_5 = PyLong_FromUnsignedLong(5ul);
    const_int_pos_7 = PyLong_FromUnsignedLong(7ul);
    const_str_empty = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 0, 0);
    const_dict_empty = _PyDict_NewPresized( 0 );
    assert(PyDict_Size(const_dict_empty) == 0);
    const_str_chr_42 = UNSTREAM_STRING_ASCII(&constant_bin[ 12718 ], 1, 0);
    const_str_chr_45 = UNSTREAM_STRING_ASCII(&constant_bin[ 13406 ], 1, 0);
    const_str_chr_58 = UNSTREAM_STRING_ASCII(&constant_bin[ 20642 ], 1, 0);
    const_str_chr_61 = UNSTREAM_STRING_ASCII(&constant_bin[ 23331 ], 1, 0);
    const_bytes_empty = UNSTREAM_BYTES(&constant_bin[ 0 ], 0);
    const_int_pos_256 = PyLong_FromUnsignedLong(256ul);
    const_str_newline = UNSTREAM_STRING_ASCII(&constant_bin[ 15791 ], 1, 0);
    const_str_plain__ = UNSTREAM_STRING_ASCII(&constant_bin[ 115 ], 1, 1);
    const_str_plain_e = UNSTREAM_STRING_ASCII(&constant_bin[ 3 ], 1, 1);
    const_str_plain_h = UNSTREAM_STRING_ASCII(&constant_bin[ 111 ], 1, 1);
    const_str_plain_i = UNSTREAM_STRING_ASCII(&constant_bin[ 10 ], 1, 1);
    const_str_plain_l = UNSTREAM_STRING_ASCII(&constant_bin[ 59 ], 1, 1);
    const_str_plain_m = UNSTREAM_STRING_ASCII(&constant_bin[ 2 ], 1, 1);
    const_str_plain_p = UNSTREAM_STRING_ASCII(&constant_bin[ 30 ], 1, 1);
    const_str_plain_r = UNSTREAM_STRING_ASCII(&constant_bin[ 31 ], 1, 1);
    const_str_plain_s = UNSTREAM_STRING_ASCII(&constant_bin[ 7 ], 1, 1);
    const_str_plain_t = UNSTREAM_STRING_ASCII(&constant_bin[ 15 ], 1, 1);
    const_str_plain_u = UNSTREAM_STRING_ASCII(&constant_bin[ 87 ], 1, 1);
    const_str_plain_x = UNSTREAM_STRING_ASCII(&constant_bin[ 464 ], 1, 1);
    const_tuple_empty = PyTuple_New(0);
    const_str_plain_cb = UNSTREAM_STRING_ASCII(&constant_bin[ 32821 ], 2, 1);
    const_str_plain_ex = UNSTREAM_STRING_ASCII(&constant_bin[ 893 ], 2, 1);
    const_str_plain_gi = UNSTREAM_STRING_ASCII(&constant_bin[ 1885 ], 2, 1);
    const_str_plain_id = UNSTREAM_STRING_ASCII(&constant_bin[ 1694 ], 2, 1);
    const_str_plain_io = UNSTREAM_STRING_ASCII(&constant_bin[ 899 ], 2, 1);
    const_str_plain_os = UNSTREAM_STRING_ASCII(&constant_bin[ 6 ], 2, 1);
    const_str_plain_rb = UNSTREAM_STRING_ASCII(&constant_bin[ 13775 ], 2, 1);
    const_str_plain_tb = UNSTREAM_STRING_ASCII(&constant_bin[ 23369 ], 2, 1);
    const_str_plain_Bus = UNSTREAM_STRING_ASCII(&constant_bin[ 1137 ], 3, 1);
    const_str_plain_END = UNSTREAM_STRING_ASCII(&constant_bin[ 26203 ], 3, 1);
    const_str_plain_RED = UNSTREAM_STRING_ASCII(&constant_bin[ 8021 ], 3, 1);
    const_str_plain__gi = UNSTREAM_STRING_ASCII(&constant_bin[ 3685 ], 3, 1);
    const_str_plain_add = UNSTREAM_STRING_ASCII(&constant_bin[ 5982 ], 3, 1);
    const_str_plain_ans = UNSTREAM_STRING_ASCII(&constant_bin[ 6150 ], 3, 1);
    const_str_plain_arg = UNSTREAM_STRING_ASCII(&constant_bin[ 32560 ], 3, 1);
    const_str_plain_buf = UNSTREAM_STRING_ASCII(&constant_bin[ 31555 ], 3, 1);
    const_str_plain_bus = UNSTREAM_STRING_ASCII(&constant_bin[ 1700 ], 3, 1);
    const_str_plain_cls = UNSTREAM_STRING_ASCII(&constant_bin[ 27710 ], 3, 1);
    const_str_plain_do_ = UNSTREAM_STRING_ASCII(&constant_bin[ 63064 ], 3, 1);
    const_str_plain_doc = UNSTREAM_STRING_ASCII(&constant_bin[ 5137 ], 3, 1);
    const_str_plain_end = UNSTREAM_STRING_ASCII(&constant_bin[ 762 ], 3, 1);
    const_str_plain_exc = UNSTREAM_STRING_ASCII(&constant_bin[ 893 ], 3, 1);
    const_str_plain_fun = UNSTREAM_STRING_ASCII(&constant_bin[ 5148 ], 3, 1);
    const_str_plain_get = UNSTREAM_STRING_ASCII(&constant_bin[ 1380 ], 3, 1);
    const_str_plain_gid = UNSTREAM_STRING_ASCII(&constant_bin[ 77084 ], 3, 1);
    const_str_plain_int = UNSTREAM_STRING_ASCII(&constant_bin[ 32 ], 3, 1);
    const_str_plain_key = UNSTREAM_STRING_ASCII(&constant_bin[ 11092 ], 3, 1);
    const_str_plain_len = UNSTREAM_STRING_ASCII(&constant_bin[ 8874 ], 3, 1);
    const_str_plain_map = UNSTREAM_STRING_ASCII(&constant_bin[ 11056 ], 3, 1);
    const_str_plain_msg = UNSTREAM_STRING_ASCII(&constant_bin[ 44384 ], 3, 1);
    const_str_plain_new = UNSTREAM_STRING_ASCII(&constant_bin[ 6022 ], 3, 1);
    const_str_plain_pg1 = UNSTREAM_STRING_ASCII(&constant_bin[ 339 ], 3, 1);
    const_str_plain_pg2 = UNSTREAM_STRING_ASCII(&constant_bin[ 364 ], 3, 1);
    const_str_plain_pg3 = UNSTREAM_STRING_ASCII(&constant_bin[ 389 ], 3, 1);
    const_str_plain_pg4 = UNSTREAM_STRING_ASCII(&constant_bin[ 414 ], 3, 1);
    const_str_plain_pg5 = UNSTREAM_STRING_ASCII(&constant_bin[ 439 ], 3, 1);
    const_str_plain_pop = UNSTREAM_STRING_ASCII(&constant_bin[ 96494 ], 3, 1);
    const_str_plain_ret = UNSTREAM_STRING_ASCII(&constant_bin[ 27497 ], 3, 1);
    const_str_plain_run = UNSTREAM_STRING_ASCII(&constant_bin[ 9886 ], 3, 1);
    const_str_plain_str = UNSTREAM_STRING_ASCII(&constant_bin[ 3583 ], 3, 1);
    const_str_plain_sum = UNSTREAM_STRING_ASCII(&constant_bin[ 25016 ], 3, 1);
    const_str_plain_sys = UNSTREAM_STRING_ASCII(&constant_bin[ 676 ], 3, 1);
    const_str_plain_typ = UNSTREAM_STRING_ASCII(&constant_bin[ 3590 ], 3, 1);
    const_str_plain_uid = UNSTREAM_STRING_ASCII(&constant_bin[ 10075 ], 3, 1);
    const_str_plain_use = UNSTREAM_STRING_ASCII(&constant_bin[ 11836 ], 3, 1);
    const_str_plain_val = UNSTREAM_STRING_ASCII(&constant_bin[ 1691 ], 3, 1);
    const_str_plain_zip = UNSTREAM_STRING_ASCII(&constant_bin[ 96497 ], 3, 1);
    const_str_plain_BOLD = UNSTREAM_STRING_ASCII(&constant_bin[ 96500 ], 4, 1);
    const_str_plain_Byte = UNSTREAM_STRING_ASCII(&constant_bin[ 27058 ], 4, 1);
    const_str_plain_args = UNSTREAM_STRING_ASCII(&constant_bin[ 39434 ], 4, 1);
    const_str_plain_argv = UNSTREAM_STRING_ASCII(&constant_bin[ 86473 ], 4, 1);
    const_str_plain_attr = UNSTREAM_STRING_ASCII(&constant_bin[ 6793 ], 4, 1);
    const_str_plain_auth = UNSTREAM_STRING_ASCII(&constant_bin[ 52576 ], 4, 1);
    const_str_plain_bool = UNSTREAM_STRING_ASCII(&constant_bin[ 7903 ], 4, 1);
    const_str_plain_conn = UNSTREAM_STRING_ASCII(&constant_bin[ 1384 ], 4, 1);
    const_str_plain_copy = UNSTREAM_STRING_ASCII(&constant_bin[ 64530 ], 4, 1);
    const_str_plain_data = UNSTREAM_STRING_ASCII(&constant_bin[ 3280 ], 4, 1);
    const_str_plain_dbus = UNSTREAM_STRING_ASCII(&constant_bin[ 2971 ], 4, 1);
    const_str_plain_ddir = UNSTREAM_STRING_ASCII(&constant_bin[ 80432 ], 4, 1);
    const_str_plain_dict = UNSTREAM_STRING_ASCII(&constant_bin[ 7491 ], 4, 1);
    const_str_plain_emit = UNSTREAM_STRING_ASCII(&constant_bin[ 40484 ], 4, 1);
    const_str_plain_exit = UNSTREAM_STRING_ASCII(&constant_bin[ 12817 ], 4, 1);
    const_str_plain_file = UNSTREAM_STRING_ASCII(&constant_bin[ 3846 ], 4, 1);
    const_str_plain_func = UNSTREAM_STRING_ASCII(&constant_bin[ 5148 ], 4, 1);
    const_str_plain_glib = UNSTREAM_STRING_ASCII(&constant_bin[ 48091 ], 4, 1);
    const_str_plain_help = UNSTREAM_STRING_ASCII(&constant_bin[ 111 ], 4, 1);
    const_str_plain_info = UNSTREAM_STRING_ASCII(&constant_bin[ 3492 ], 4, 1);
    const_str_plain_is_a = UNSTREAM_STRING_ASCII(&constant_bin[ 96504 ], 4, 1);
    const_str_plain_iter = UNSTREAM_STRING_ASCII(&constant_bin[ 44553 ], 4, 1);
    const_str_plain_join = UNSTREAM_STRING_ASCII(&constant_bin[ 96508 ], 4, 1);
    const_str_plain_keys = UNSTREAM_STRING_ASCII(&constant_bin[ 43552 ], 4, 1);
    const_str_plain_list = UNSTREAM_STRING_ASCII(&constant_bin[ 23613 ], 4, 1);
    const_str_plain_look = UNSTREAM_STRING_ASCII(&constant_bin[ 12659 ], 4, 1);
    const_str_plain_name = UNSTREAM_STRING_ASCII(&constant_bin[ 0 ], 4, 1);
    const_str_plain_open = UNSTREAM_STRING_ASCII(&constant_bin[ 8899 ], 4, 1);
    const_str_plain_path = UNSTREAM_STRING_ASCII(&constant_bin[ 828 ], 4, 1);
    const_str_plain_prob = UNSTREAM_STRING_ASCII(&constant_bin[ 8788 ], 4, 1);
    const_str_plain_read = UNSTREAM_STRING_ASCII(&constant_bin[ 2465 ], 4, 1);
    const_str_plain_recv = UNSTREAM_STRING_ASCII(&constant_bin[ 96512 ], 4, 1);
    const_str_plain_repr = UNSTREAM_STRING_ASCII(&constant_bin[ 1550 ], 4, 1);
    const_str_plain_rule = UNSTREAM_STRING_ASCII(&constant_bin[ 35116 ], 4, 1);
    const_str_plain_self = UNSTREAM_STRING_ASCII(&constant_bin[ 30082 ], 4, 1);
    const_str_plain_send = UNSTREAM_STRING_ASCII(&constant_bin[ 761 ], 4, 1);
    const_str_plain_site = UNSTREAM_STRING_ASCII(&constant_bin[ 23811 ], 4, 1);
    const_str_plain_time = UNSTREAM_STRING_ASCII(&constant_bin[ 7354 ], 4, 1);
    const_str_plain_type = UNSTREAM_STRING_ASCII(&constant_bin[ 3590 ], 4, 1);
    const_str_plain_uuid = UNSTREAM_STRING_ASCII(&constant_bin[ 10074 ], 4, 1);
    const_str_plain_void = UNSTREAM_STRING_ASCII(&constant_bin[ 96516 ], 4, 1);
    const_str_plain_warn = UNSTREAM_STRING_ASCII(&constant_bin[ 5674 ], 4, 1);
    const_float_minus_0_0 = UNSTREAM_FLOAT(&constant_bin[ 96520 ]);
    const_float_minus_1_0 = UNSTREAM_FLOAT(&constant_bin[ 96528 ]);
    const_str_plain_Array = UNSTREAM_STRING_ASCII(&constant_bin[ 27062 ], 5, 1);
    const_str_plain_ERROR = UNSTREAM_STRING_ASCII(&constant_bin[ 47634 ], 5, 1);
    const_str_plain_False = UNSTREAM_STRING_ASCII(&constant_bin[ 40802 ], 5, 1);
    const_str_plain_GEnum = UNSTREAM_STRING_ASCII(&constant_bin[ 96536 ], 5, 1);
    const_str_plain_GTKIO = UNSTREAM_STRING_ASCII(&constant_bin[ 83643 ], 5, 1);
    const_str_plain_GType = UNSTREAM_STRING_ASCII(&constant_bin[ 63757 ], 5, 1);
    const_str_plain_Int16 = UNSTREAM_STRING_ASCII(&constant_bin[ 27095 ], 5, 1);
    const_str_plain_Int32 = UNSTREAM_STRING_ASCII(&constant_bin[ 27110 ], 5, 1);
    const_str_plain_Int64 = UNSTREAM_STRING_ASCII(&constant_bin[ 27125 ], 5, 1);
    const_str_plain_bases = UNSTREAM_STRING_ASCII(&constant_bin[ 7093 ], 5, 1);
    const_str_plain_bytes = UNSTREAM_STRING_ASCII(&constant_bin[ 87634 ], 5, 1);
    const_str_plain_chown = UNSTREAM_STRING_ASCII(&constant_bin[ 79289 ], 5, 1);
    const_str_plain_clear = UNSTREAM_STRING_ASCII(&constant_bin[ 22834 ], 5, 1);
    const_str_plain_close = UNSTREAM_STRING_ASCII(&constant_bin[ 12066 ], 5, 1);
    const_str_plain_color = UNSTREAM_STRING_ASCII(&constant_bin[ 57 ], 5, 1);
    const_str_plain_debug = UNSTREAM_STRING_ASCII(&constant_bin[ 96541 ], 5, 1);
    const_str_plain_dict_ = UNSTREAM_STRING_ASCII(&constant_bin[ 96546 ], 5, 1);
    const_str_plain_error = UNSTREAM_STRING_ASCII(&constant_bin[ 3457 ], 5, 1);
    const_str_plain_field = UNSTREAM_STRING_ASCII(&constant_bin[ 10547 ], 5, 1);
    const_str_plain_flags = UNSTREAM_STRING_ASCII(&constant_bin[ 5976 ], 5, 1);
    const_str_plain_float = UNSTREAM_STRING_ASCII(&constant_bin[ 59982 ], 5, 1);
    const_str_plain_iface = UNSTREAM_STRING_ASCII(&constant_bin[ 31528 ], 5, 1);
    const_str_plain_input = UNSTREAM_STRING_ASCII(&constant_bin[ 84 ], 5, 1);
    const_str_plain_items = UNSTREAM_STRING_ASCII(&constant_bin[ 78288 ], 5, 1);
    const_str_plain_klass = UNSTREAM_STRING_ASCII(&constant_bin[ 75413 ], 5, 1);
    const_str_plain_level = UNSTREAM_STRING_ASCII(&constant_bin[ 5720 ], 5, 1);
    const_str_plain_limit = UNSTREAM_STRING_ASCII(&constant_bin[ 77936 ], 5, 1);
    const_str_plain_long_ = UNSTREAM_STRING_ASCII(&constant_bin[ 4778 ], 5, 1);
    const_str_plain_lower = UNSTREAM_STRING_ASCII(&constant_bin[ 63447 ], 5, 1);
    const_str_plain_match = UNSTREAM_STRING_ASCII(&constant_bin[ 279 ], 5, 1);
    const_str_plain_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 32693 ], 5, 1);
    const_str_plain_print = UNSTREAM_STRING_ASCII(&constant_bin[ 30 ], 5, 1);
    const_str_plain_proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 33113 ], 5, 1);
    const_str_plain_range = UNSTREAM_STRING_ASCII(&constant_bin[ 16783 ], 5, 1);
    const_str_plain_split = UNSTREAM_STRING_ASCII(&constant_bin[ 23633 ], 5, 1);
    const_str_plain_strip = UNSTREAM_STRING_ASCII(&constant_bin[ 71538 ], 5, 1);
    const_str_plain_throw = UNSTREAM_STRING_ASCII(&constant_bin[ 96551 ], 5, 1);
    const_str_plain_tools = UNSTREAM_STRING_ASCII(&constant_bin[ 6900 ], 5, 1);
    const_str_plain_tuple = UNSTREAM_STRING_ASCII(&constant_bin[ 2848 ], 5, 1);
    const_str_plain_type_ = UNSTREAM_STRING_ASCII(&constant_bin[ 5175 ], 5, 1);
    const_str_plain_types = UNSTREAM_STRING_ASCII(&constant_bin[ 3590 ], 5, 1);
    const_str_plain_value = UNSTREAM_STRING_ASCII(&constant_bin[ 42799 ], 5, 1);
    const_str_plain_watch = UNSTREAM_STRING_ASCII(&constant_bin[ 8590 ], 5, 1);
    const_str_angle_lambda = UNSTREAM_STRING_ASCII(&constant_bin[ 23960 ], 8, 0);
    const_str_plain_Double = UNSTREAM_STRING_ASCII(&constant_bin[ 27140 ], 6, 1);
    const_str_plain_GBoxed = UNSTREAM_STRING_ASCII(&constant_bin[ 96556 ], 6, 1);
    const_str_plain_GFlags = UNSTREAM_STRING_ASCII(&constant_bin[ 96562 ], 6, 1);
    const_str_plain_NewtIO = UNSTREAM_STRING_ASCII(&constant_bin[ 9700 ], 6, 1);
    const_str_plain_PURPLE = UNSTREAM_STRING_ASCII(&constant_bin[ 96568 ], 6, 1);
    const_str_plain_String = UNSTREAM_STRING_ASCII(&constant_bin[ 2403 ], 6, 1);
    const_str_plain_Struct = UNSTREAM_STRING_ASCII(&constant_bin[ 5379 ], 6, 1);
    const_str_plain_TextIO = UNSTREAM_STRING_ASCII(&constant_bin[ 9633 ], 6, 1);
    const_str_plain_UInt16 = UNSTREAM_STRING_ASCII(&constant_bin[ 27102 ], 6, 1);
    const_str_plain_UInt32 = UNSTREAM_STRING_ASCII(&constant_bin[ 27117 ], 6, 1);
    const_str_plain_UInt64 = UNSTREAM_STRING_ASCII(&constant_bin[ 27132 ], 6, 1);
    const_str_plain__proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 53052 ], 6, 1);
    const_str_plain_append = UNSTREAM_STRING_ASCII(&constant_bin[ 57238 ], 6, 1);
    const_str_plain_create = UNSTREAM_STRING_ASCII(&constant_bin[ 15828 ], 6, 1);
    const_str_plain_decode = UNSTREAM_STRING_ASCII(&constant_bin[ 96574 ], 6, 1);
    const_str_plain_delete = UNSTREAM_STRING_ASCII(&constant_bin[ 70825 ], 6, 1);
    const_str_plain_encode = UNSTREAM_STRING_ASCII(&constant_bin[ 96580 ], 6, 1);
    const_str_plain_extend = UNSTREAM_STRING_ASCII(&constant_bin[ 96586 ], 6, 1);
    const_str_plain_format = UNSTREAM_STRING_ASCII(&constant_bin[ 23345 ], 6, 1);
    const_str_plain_g_type = UNSTREAM_STRING_ASCII(&constant_bin[ 3588 ], 6, 1);
    const_str_plain_getpid = UNSTREAM_STRING_ASCII(&constant_bin[ 96592 ], 6, 1);
    const_str_plain_getter = UNSTREAM_STRING_ASCII(&constant_bin[ 60960 ], 6, 1);
    const_str_plain_getuid = UNSTREAM_STRING_ASCII(&constant_bin[ 96598 ], 6, 1);
    const_str_plain_ignore = UNSTREAM_STRING_ASCII(&constant_bin[ 35182 ], 6, 1);
    const_str_plain_is_py2 = UNSTREAM_STRING_ASCII(&constant_bin[ 1069 ], 6, 1);
    const_str_plain_is_py3 = UNSTREAM_STRING_ASCII(&constant_bin[ 2375 ], 6, 1);
    const_str_plain_kwargs = UNSTREAM_STRING_ASCII(&constant_bin[ 71586 ], 6, 1);
    const_str_plain_locals = UNSTREAM_STRING_ASCII(&constant_bin[ 23853 ], 6, 1);
    const_str_plain_member = UNSTREAM_STRING_ASCII(&constant_bin[ 2255 ], 6, 1);
    const_str_plain_method = UNSTREAM_STRING_ASCII(&constant_bin[ 1422 ], 6, 1);
    const_str_plain_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5809 ], 6, 1);
    const_str_plain_object = UNSTREAM_STRING_ASCII(&constant_bin[ 2342 ], 6, 1);
    const_str_plain_origin = UNSTREAM_STRING_ASCII(&constant_bin[ 34154 ], 6, 1);
    const_str_plain_pytype = UNSTREAM_STRING_ASCII(&constant_bin[ 5346 ], 6, 1);
    const_str_plain_reason = UNSTREAM_STRING_ASCII(&constant_bin[ 8729 ], 6, 1);
    const_str_plain_remove = UNSTREAM_STRING_ASCII(&constant_bin[ 33001 ], 6, 1);
    const_str_plain_report = UNSTREAM_STRING_ASCII(&constant_bin[ 8682 ], 6, 1);
    const_str_plain_result = UNSTREAM_STRING_ASCII(&constant_bin[ 68477 ], 6, 1);
    const_str_plain_rsplit = UNSTREAM_STRING_ASCII(&constant_bin[ 26216 ], 6, 1);
    const_str_plain_screen = UNSTREAM_STRING_ASCII(&constant_bin[ 975 ], 6, 1);
    const_str_plain_setter = UNSTREAM_STRING_ASCII(&constant_bin[ 60119 ], 6, 1);
    const_str_plain_socket = UNSTREAM_STRING_ASCII(&constant_bin[ 96604 ], 6, 1);
    const_str_plain_syslog = UNSTREAM_STRING_ASCII(&constant_bin[ 733 ], 6, 1);
    const_str_plain_system = UNSTREAM_STRING_ASCII(&constant_bin[ 1487 ], 6, 1);
    const_str_plain_update = UNSTREAM_STRING_ASCII(&constant_bin[ 74185 ], 6, 1);
    const_tuple_none_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    const_str_angle_genexpr = UNSTREAM_STRING_ASCII(&constant_bin[ 67476 ], 9, 0);
    const_str_plain_AF_UNIX = UNSTREAM_STRING_ASCII(&constant_bin[ 96610 ], 7, 1);
    const_str_plain_Boolean = UNSTREAM_STRING_ASCII(&constant_bin[ 27086 ], 7, 1);
    const_str_plain_GObject = UNSTREAM_STRING_ASCII(&constant_bin[ 6305 ], 7, 1);
    const_str_plain_SHUT_WR = UNSTREAM_STRING_ASCII(&constant_bin[ 96617 ], 7, 1);
    const_str_plain_Unknown = UNSTREAM_STRING_ASCII(&constant_bin[ 8534 ], 7, 1);
    const_str_plain___all__ = UNSTREAM_STRING_ASCII(&constant_bin[ 1040 ], 7, 1);
    const_str_plain___cmp__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96624 ], 7, 1);
    const_str_plain___dir__ = UNSTREAM_STRING_ASCII(&constant_bin[ 70063 ], 7, 1);
    const_str_plain___doc__ = UNSTREAM_STRING_ASCII(&constant_bin[ 76081 ], 7, 1);
    const_str_plain___get__ = UNSTREAM_STRING_ASCII(&constant_bin[ 63706 ], 7, 1);
    const_str_plain___new__ = UNSTREAM_STRING_ASCII(&constant_bin[ 30697 ], 7, 1);
    const_str_plain___set__ = UNSTREAM_STRING_ASCII(&constant_bin[ 62669 ], 7, 1);
    const_str_plain___str__ = UNSTREAM_STRING_ASCII(&constant_bin[ 46085 ], 7, 1);
    const_str_plain__compat = UNSTREAM_STRING_ASCII(&constant_bin[ 27436 ], 7, 1);
    const_str_plain__logger = UNSTREAM_STRING_ASCII(&constant_bin[ 1911 ], 7, 1);
    const_str_plain_abspath = UNSTREAM_STRING_ASCII(&constant_bin[ 96631 ], 7, 1);
    const_str_plain_acquire = UNSTREAM_STRING_ASCII(&constant_bin[ 96638 ], 7, 1);
    const_str_plain_aliases = UNSTREAM_STRING_ASCII(&constant_bin[ 175 ], 7, 1);
    const_str_plain_compile = UNSTREAM_STRING_ASCII(&constant_bin[ 96645 ], 7, 1);
    const_str_plain_connect = UNSTREAM_STRING_ASCII(&constant_bin[ 1384 ], 7, 1);
    const_str_plain_delattr = UNSTREAM_STRING_ASCII(&constant_bin[ 7958 ], 7, 1);
    const_str_plain_duphash = UNSTREAM_STRING_ASCII(&constant_bin[ 96652 ], 7, 1);
    const_str_plain_examine = UNSTREAM_STRING_ASCII(&constant_bin[ 11084 ], 7, 1);
    const_str_plain_getattr = UNSTREAM_STRING_ASCII(&constant_bin[ 7987 ], 7, 1);
    const_str_plain_globals = UNSTREAM_STRING_ASCII(&constant_bin[ 9955 ], 7, 1);
    const_str_plain_gobject = UNSTREAM_STRING_ASCII(&constant_bin[ 3902 ], 7, 1);
    const_str_plain_inspect = UNSTREAM_STRING_ASCII(&constant_bin[ 7747 ], 7, 1);
    const_str_plain_isdigit = UNSTREAM_STRING_ASCII(&constant_bin[ 96659 ], 7, 1);
    const_str_plain_logging = UNSTREAM_STRING_ASCII(&constant_bin[ 1882 ], 7, 1);
    const_str_plain_matches = UNSTREAM_STRING_ASCII(&constant_bin[ 279 ], 7, 1);
    const_str_plain_modules = UNSTREAM_STRING_ASCII(&constant_bin[ 6637 ], 7, 1);
    const_str_plain_pkgutil = UNSTREAM_STRING_ASCII(&constant_bin[ 96666 ], 7, 1);
    const_str_plain_private = UNSTREAM_STRING_ASCII(&constant_bin[ 27824 ], 7, 1);
    const_str_plain_problem = UNSTREAM_STRING_ASCII(&constant_bin[ 8788 ], 7, 1);
    const_str_plain_proxies = UNSTREAM_STRING_ASCII(&constant_bin[ 7517 ], 7, 1);
    const_str_plain_release = UNSTREAM_STRING_ASCII(&constant_bin[ 8934 ], 7, 1);
    const_str_plain_replace = UNSTREAM_STRING_ASCII(&constant_bin[ 71146 ], 7, 1);
    const_str_plain_sendall = UNSTREAM_STRING_ASCII(&constant_bin[ 96673 ], 7, 1);
    const_str_plain_timeout = UNSTREAM_STRING_ASCII(&constant_bin[ 85464 ], 7, 1);
    const_str_plain_unicode = UNSTREAM_STRING_ASCII(&constant_bin[ 2941 ], 7, 1);
    const_str_plain_version = UNSTREAM_STRING_ASCII(&constant_bin[ 3484 ], 7, 1);
    const_str_plain_weakref = UNSTREAM_STRING_ASCII(&constant_bin[ 1940 ], 7, 1);
    const_str_plain_wrapper = UNSTREAM_STRING_ASCII(&constant_bin[ 28381 ], 7, 1);
    const_tuple_false_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_false_tuple, 0, Py_False); Py_INCREF(Py_False);
    const_tuple_int_0_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_0_tuple, 0, const_int_0); Py_INCREF(const_int_0);
    const_str_angle_listcomp = UNSTREAM_STRING_ASCII(&constant_bin[ 96680 ], 10, 0);
    const_str_plain_TYPE_INT = UNSTREAM_STRING_ASCII(&constant_bin[ 4033 ], 8, 1);
    const_str_plain___call__ = UNSTREAM_STRING_ASCII(&constant_bin[ 52038 ], 8, 1);
    const_str_plain___dict__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96690 ], 8, 1);
    const_str_plain___exit__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96698 ], 8, 1);
    const_str_plain___file__ = UNSTREAM_STRING_ASCII(&constant_bin[ 3844 ], 8, 1);
    const_str_plain___info__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96706 ], 8, 1);
    const_str_plain___init__ = UNSTREAM_STRING_ASCII(&constant_bin[ 26693 ], 8, 1);
    const_str_plain___iter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 89565 ], 8, 1);
    const_str_plain___main__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96714 ], 8, 1);
    const_str_plain___name__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96722 ], 8, 1);
    const_str_plain___path__ = UNSTREAM_STRING_ASCII(&constant_bin[ 1010 ], 8, 1);
    const_str_plain___repr__ = UNSTREAM_STRING_ASCII(&constant_bin[ 1548 ], 8, 1);
    const_str_plain___spec__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96730 ], 8, 1);
    const_str_plain__probdir = UNSTREAM_STRING_ASCII(&constant_bin[ 96738 ], 8, 1);
    const_str_plain_bus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 1700 ], 8, 1);
    const_str_plain_callable = UNSTREAM_STRING_ASCII(&constant_bin[ 5421 ], 8, 1);
    const_str_plain_callback = UNSTREAM_STRING_ASCII(&constant_bin[ 34787 ], 8, 1);
    const_str_plain_commands = UNSTREAM_STRING_ASCII(&constant_bin[ 145 ], 8, 1);
    const_str_plain_datetime = UNSTREAM_STRING_ASCII(&constant_bin[ 7622 ], 8, 1);
    const_str_plain_del_item = UNSTREAM_STRING_ASCII(&constant_bin[ 80512 ], 8, 1);
    const_str_plain_endswith = UNSTREAM_STRING_ASCII(&constant_bin[ 96746 ], 8, 1);
    const_str_plain_exc_info = UNSTREAM_STRING_ASCII(&constant_bin[ 96754 ], 8, 1);
    const_str_plain_fromlist = UNSTREAM_STRING_ASCII(&constant_bin[ 96762 ], 8, 1);
    const_str_plain_funcName = UNSTREAM_STRING_ASCII(&constant_bin[ 96770 ], 8, 1);
    const_str_plain_get_item = UNSTREAM_STRING_ASCII(&constant_bin[ 80786 ], 8, 1);
    const_str_plain_get_name = UNSTREAM_STRING_ASCII(&constant_bin[ 32684 ], 8, 1);
    const_str_plain_get_size = UNSTREAM_STRING_ASCII(&constant_bin[ 96778 ], 8, 1);
    const_str_plain_importer = UNSTREAM_STRING_ASCII(&constant_bin[ 68631 ], 8, 1);
    const_str_plain_instance = UNSTREAM_STRING_ASCII(&constant_bin[ 7873 ], 8, 1);
    const_str_plain_keywords = UNSTREAM_STRING_ASCII(&constant_bin[ 96786 ], 8, 1);
    const_str_plain_list_all = UNSTREAM_STRING_ASCII(&constant_bin[ 80358 ], 8, 1);
    const_str_plain_mainloop = UNSTREAM_STRING_ASCII(&constant_bin[ 27363 ], 8, 1);
    const_str_plain_override = UNSTREAM_STRING_ASCII(&constant_bin[ 5879 ], 8, 1);
    const_str_plain_property = UNSTREAM_STRING_ASCII(&constant_bin[ 1350 ], 8, 1);
    const_str_plain_set_item = UNSTREAM_STRING_ASCII(&constant_bin[ 80336 ], 8, 1);
    const_str_plain_shutdown = UNSTREAM_STRING_ASCII(&constant_bin[ 96794 ], 8, 1);
    const_str_plain_strftime = UNSTREAM_STRING_ASCII(&constant_bin[ 96802 ], 8, 1);
    const_str_plain_warnings = UNSTREAM_STRING_ASCII(&constant_bin[ 5674 ], 8, 1);
    const_str_angle_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 96810 ], 11, 0);
    const_str_plain_ByteArray = UNSTREAM_STRING_ASCII(&constant_bin[ 27058 ], 9, 1);
    const_str_plain_Interface = UNSTREAM_STRING_ASCII(&constant_bin[ 3306 ], 9, 1);
    const_str_plain_Signature = UNSTREAM_STRING_ASCII(&constant_bin[ 27069 ], 9, 1);
    const_str_plain_SystemBus = UNSTREAM_STRING_ASCII(&constant_bin[ 1194 ], 9, 1);
    const_str_plain_TYPE_CHAR = UNSTREAM_STRING_ASCII(&constant_bin[ 4069 ], 9, 1);
    const_str_plain_TYPE_ENUM = UNSTREAM_STRING_ASCII(&constant_bin[ 4685 ], 9, 1);
    const_str_plain_TYPE_LONG = UNSTREAM_STRING_ASCII(&constant_bin[ 4196 ], 9, 1);
    const_str_plain_TYPE_NONE = UNSTREAM_STRING_ASCII(&constant_bin[ 4002 ], 9, 1);
    const_str_plain_TYPE_STRV = UNSTREAM_STRING_ASCII(&constant_bin[ 4620 ], 9, 1);
    const_str_plain_TYPE_UINT = UNSTREAM_STRING_ASCII(&constant_bin[ 3971 ], 9, 1);
    const_str_plain_VFuncInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5245 ], 9, 1);
    const_str_plain___class__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96821 ], 9, 1);
    const_str_plain___debug__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96830 ], 9, 1);
    const_str_plain___enter__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96839 ], 9, 1);
    const_str_plain___gtype__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96848 ], 9, 1);
    const_str_plain___slots__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96857 ], 9, 1);
    const_str_plain_burnedout = UNSTREAM_STRING_ASCII(&constant_bin[ 308 ], 9, 1);
    const_str_plain_bytearray = UNSTREAM_STRING_ASCII(&constant_bin[ 96866 ], 9, 1);
    const_str_plain_exception = UNSTREAM_STRING_ASCII(&constant_bin[ 893 ], 9, 1);
    const_str_plain_getLogger = UNSTREAM_STRING_ASCII(&constant_bin[ 90250 ], 9, 1);
    const_str_plain_get_proxy = UNSTREAM_STRING_ASCII(&constant_bin[ 96875 ], 9, 1);
    const_str_plain_get_value = UNSTREAM_STRING_ASCII(&constant_bin[ 69783 ], 9, 1);
    const_str_plain_importlib = UNSTREAM_STRING_ASCII(&constant_bin[ 3710 ], 9, 1);
    const_str_plain_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 2297 ], 9, 1);
    const_str_plain_inventory = UNSTREAM_STRING_ASCII(&constant_bin[ 204 ], 9, 1);
    const_str_plain_metaclass = UNSTREAM_STRING_ASCII(&constant_bin[ 62984 ], 9, 1);
    const_str_plain_namespace = UNSTREAM_STRING_ASCII(&constant_bin[ 58302 ], 9, 1);
    const_str_plain_overrides = UNSTREAM_STRING_ASCII(&constant_bin[ 5879 ], 9, 1);
    const_str_plain_signature = UNSTREAM_STRING_ASCII(&constant_bin[ 33756 ], 9, 1);
    const_str_plain_threading = UNSTREAM_STRING_ASCII(&constant_bin[ 2463 ], 9, 1);
    const_str_plain_traceback = UNSTREAM_STRING_ASCII(&constant_bin[ 10390 ], 9, 1);
    const_tuple_str_dot_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_dot_tuple, 0, const_str_dot); Py_INCREF(const_str_dot);
    const_slice_none_none_none = PySlice_New(Py_None, Py_None, Py_None);
    const_str_plain_BUS_SYSTEM = UNSTREAM_STRING_ASCII(&constant_bin[ 1162 ], 10, 1);
    const_str_plain_Connection = UNSTREAM_STRING_ASCII(&constant_bin[ 1293 ], 10, 1);
    const_str_plain_Dictionary = UNSTREAM_STRING_ASCII(&constant_bin[ 27171 ], 10, 1);
    const_str_plain_GInterface = UNSTREAM_STRING_ASCII(&constant_bin[ 6438 ], 10, 1);
    const_str_plain_LOCAL_PATH = UNSTREAM_STRING_ASCII(&constant_bin[ 2647 ], 10, 1);
    const_str_plain_ModuleType = UNSTREAM_STRING_ASCII(&constant_bin[ 96884 ], 10, 1);
    const_str_plain_ObjectInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5460 ], 10, 1);
    const_str_plain_ObjectPath = UNSTREAM_STRING_ASCII(&constant_bin[ 27046 ], 10, 1);
    const_str_plain_Repository = UNSTREAM_STRING_ASCII(&constant_bin[ 3551 ], 10, 1);
    const_str_plain_SessionBus = UNSTREAM_STRING_ASCII(&constant_bin[ 1130 ], 10, 1);
    const_str_plain_StarterBus = UNSTREAM_STRING_ASCII(&constant_bin[ 1258 ], 10, 1);
    const_str_plain_StructInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5379 ], 10, 1);
    const_str_plain_StructMeta = UNSTREAM_STRING_ASCII(&constant_bin[ 6556 ], 10, 1);
    const_str_plain_TYPE_BOXED = UNSTREAM_STRING_ASCII(&constant_bin[ 4423 ], 10, 1);
    const_str_plain_TYPE_FLAGS = UNSTREAM_STRING_ASCII(&constant_bin[ 4716 ], 10, 1);
    const_str_plain_TYPE_FLOAT = UNSTREAM_STRING_ASCII(&constant_bin[ 4324 ], 10, 1);
    const_str_plain_TYPE_GTYPE = UNSTREAM_STRING_ASCII(&constant_bin[ 4588 ], 10, 1);
    const_str_plain_TYPE_INT64 = UNSTREAM_STRING_ASCII(&constant_bin[ 4259 ], 10, 1);
    const_str_plain_TYPE_PARAM = UNSTREAM_STRING_ASCII(&constant_bin[ 4455 ], 10, 1);
    const_str_plain_TYPE_UCHAR = UNSTREAM_STRING_ASCII(&constant_bin[ 4100 ], 10, 1);
    const_str_plain_TYPE_ULONG = UNSTREAM_STRING_ASCII(&constant_bin[ 4227 ], 10, 1);
    const_str_plain_UTF8String = UNSTREAM_STRING_ASCII(&constant_bin[ 2431 ], 10, 1);
    const_str_plain___cached__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96894 ], 10, 1);
    const_str_plain___import__ = UNSTREAM_STRING_ASCII(&constant_bin[ 9923 ], 10, 1);
    const_str_plain___loader__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96904 ], 10, 1);
    const_str_plain___module__ = UNSTREAM_STRING_ASCII(&constant_bin[ 96914 ], 10, 1);
    const_str_plain__constants = UNSTREAM_STRING_ASCII(&constant_bin[ 59964 ], 10, 1);
    const_str_plain__persisted = UNSTREAM_STRING_ASCII(&constant_bin[ 96924 ], 10, 1);
    const_str_plain_call_async = UNSTREAM_STRING_ASCII(&constant_bin[ 44727 ], 10, 1);
    const_str_plain_exceptions = UNSTREAM_STRING_ASCII(&constant_bin[ 47125 ], 10, 1);
    const_str_plain_executable = UNSTREAM_STRING_ASCII(&constant_bin[ 23321 ], 10, 1);
    const_str_plain_get_g_type = UNSTREAM_STRING_ASCII(&constant_bin[ 96934 ], 10, 1);
    const_str_plain_get_object = UNSTREAM_STRING_ASCII(&constant_bin[ 39322 ], 10, 1);
    const_str_plain_identifier = UNSTREAM_STRING_ASCII(&constant_bin[ 78207 ], 10, 1);
    const_str_plain_introspect = UNSTREAM_STRING_ASCII(&constant_bin[ 3266 ], 10, 1);
    const_str_plain_isinstance = UNSTREAM_STRING_ASCII(&constant_bin[ 7871 ], 10, 1);
    const_str_plain_issubclass = UNSTREAM_STRING_ASCII(&constant_bin[ 96944 ], 10, 1);
    const_str_plain_pressenter = UNSTREAM_STRING_ASCII(&constant_bin[ 96954 ], 10, 1);
    const_str_plain_problemify = UNSTREAM_STRING_ASCII(&constant_bin[ 96964 ], 10, 1);
    const_str_plain_pyanaconda = UNSTREAM_STRING_ASCII(&constant_bin[ 82162 ], 10, 1);
    const_str_plain_repository = UNSTREAM_STRING_ASCII(&constant_bin[ 5618 ], 10, 1);
    const_str_plain_setdefault = UNSTREAM_STRING_ASCII(&constant_bin[ 96974 ], 10, 1);
    const_str_plain_settimeout = UNSTREAM_STRING_ASCII(&constant_bin[ 96984 ], 10, 1);
    const_str_plain_stacklevel = UNSTREAM_STRING_ASCII(&constant_bin[ 5715 ], 10, 1);
    const_str_plain_startswith = UNSTREAM_STRING_ASCII(&constant_bin[ 96994 ], 10, 1);
    const_tuple_type_str_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_str_tuple, 0, (PyObject *)&PyUnicode_Type); Py_INCREF((PyObject *)&PyUnicode_Type);
    const_str_plain_AuthFailure = UNSTREAM_STRING_ASCII(&constant_bin[ 81066 ], 11, 1);
    const_str_plain_BUS_SESSION = UNSTREAM_STRING_ASCII(&constant_bin[ 1097 ], 11, 1);
    const_str_plain_BUS_STARTER = UNSTREAM_STRING_ASCII(&constant_bin[ 1225 ], 11, 1);
    const_str_plain_GObjectMeta = UNSTREAM_STRING_ASCII(&constant_bin[ 6305 ], 11, 1);
    const_str_plain_HAVE_POLKIT = UNSTREAM_STRING_ASCII(&constant_bin[ 97004 ], 11, 1);
    const_str_plain_ImportError = UNSTREAM_STRING_ASCII(&constant_bin[ 8617 ], 11, 1);
    const_str_plain_LOCAL_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 2614 ], 11, 1);
    const_str_plain_ProxyObject = UNSTREAM_STRING_ASCII(&constant_bin[ 2908 ], 11, 1);
    const_str_plain_PyGIWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 3811 ], 11, 1);
    const_str_plain_SOCK_STREAM = UNSTREAM_STRING_ASCII(&constant_bin[ 97015 ], 11, 1);
    const_str_plain_TYPE_DOUBLE = UNSTREAM_STRING_ASCII(&constant_bin[ 4356 ], 11, 1);
    const_str_plain_TYPE_OBJECT = UNSTREAM_STRING_ASCII(&constant_bin[ 4487 ], 11, 1);
    const_str_plain_TYPE_STRING = UNSTREAM_STRING_ASCII(&constant_bin[ 4520 ], 11, 1);
    const_str_plain_TYPE_SYSTEM = UNSTREAM_STRING_ASCII(&constant_bin[ 27732 ], 11, 1);
    const_str_plain_TYPE_UINT64 = UNSTREAM_STRING_ASCII(&constant_bin[ 4291 ], 11, 1);
    const_str_plain___getattr__ = UNSTREAM_STRING_ASCII(&constant_bin[ 52671 ], 11, 1);
    const_str_plain___getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 78435 ], 11, 1);
    const_str_plain___package__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97026 ], 11, 1);
    const_str_plain___prepare__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97037 ], 11, 1);
    const_str_plain___version__ = UNSTREAM_STRING_ASCII(&constant_bin[ 3518 ], 11, 1);
    const_str_plain__connection = UNSTREAM_STRING_ASCII(&constant_bin[ 1383 ], 11, 1);
    const_str_plain_basicConfig = UNSTREAM_STRING_ASCII(&constant_bin[ 97048 ], 11, 1);
    const_str_plain_classmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 97059 ], 11, 1);
    const_str_plain_collections = UNSTREAM_STRING_ASCII(&constant_bin[ 97070 ], 11, 1);
    const_str_plain_extend_path = UNSTREAM_STRING_ASCII(&constant_bin[ 97081 ], 11, 1);
    const_str_plain_get_default = UNSTREAM_STRING_ASCII(&constant_bin[ 26424 ], 11, 1);
    const_str_plain_get_methods = UNSTREAM_STRING_ASCII(&constant_bin[ 97092 ], 11, 1);
    const_str_plain_get_version = UNSTREAM_STRING_ASCII(&constant_bin[ 97103 ], 11, 1);
    const_str_plain_method_info = UNSTREAM_STRING_ASCII(&constant_bin[ 97114 ], 11, 1);
    const_str_plain_object_path = UNSTREAM_STRING_ASCII(&constant_bin[ 2342 ], 11, 1);
    const_str_plain_signal_name = UNSTREAM_STRING_ASCII(&constant_bin[ 39930 ], 11, 1);
    const_tuple_int_pos_5_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_5_tuple, 0, const_int_pos_5); Py_INCREF(const_int_pos_5);
    const_tuple_str_empty_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_empty_tuple, 0, const_str_empty); Py_INCREF(const_str_empty);
    const_str_plain_CallableInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5538 ], 12, 1);
    const_str_plain_ErrorMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2786 ], 12, 1);
    const_str_plain_FunctionInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 5276 ], 12, 1);
    const_str_plain_TYPE_BOOLEAN = UNSTREAM_STRING_ASCII(&constant_bin[ 4162 ], 12, 1);
    const_str_plain_TYPE_INVALID = UNSTREAM_STRING_ASCII(&constant_bin[ 6862 ], 12, 1);
    const_str_plain_TYPE_POINTER = UNSTREAM_STRING_ASCII(&constant_bin[ 4389 ], 12, 1);
    const_str_plain_TYPE_SESSION = UNSTREAM_STRING_ASCII(&constant_bin[ 2212 ], 12, 1);
    const_str_plain_TYPE_STARTER = UNSTREAM_STRING_ASCII(&constant_bin[ 27751 ], 12, 1);
    const_str_plain_TYPE_VARIANT = UNSTREAM_STRING_ASCII(&constant_bin[ 4651 ], 12, 1);
    const_str_plain___builtins__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97125 ], 12, 1);
    const_str_plain___compiled__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97137 ], 12, 1);
    const_str_plain___qualname__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97149 ], 12, 1);
    const_str_plain_has_location = UNSTREAM_STRING_ASCII(&constant_bin[ 97161 ], 12, 1);
    const_str_plain_help_command = UNSTREAM_STRING_ASCII(&constant_bin[ 111 ], 12, 1);
    const_str_plain_outofmatches = UNSTREAM_STRING_ASCII(&constant_bin[ 274 ], 12, 1);
    const_str_plain_problem_data = UNSTREAM_STRING_ASCII(&constant_bin[ 9535 ], 12, 1);
    const_str_plain_staticmethod = UNSTREAM_STRING_ASCII(&constant_bin[ 1416 ], 12, 1);
    const_str_plain_string_types = UNSTREAM_STRING_ASCII(&constant_bin[ 3583 ], 12, 1);
    const_str_plain_threads_init = UNSTREAM_STRING_ASCII(&constant_bin[ 3013 ], 12, 1);
    const_str_plain_utf8_strings = UNSTREAM_STRING_ASCII(&constant_bin[ 39388 ], 12, 1);
    const_str_plain_version_info = UNSTREAM_STRING_ASCII(&constant_bin[ 3484 ], 12, 1);
    const_tuple_str_chr_42_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_chr_42_tuple, 0, const_str_chr_42); Py_INCREF(const_str_chr_42);
    const_tuple_true_false_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_true_false_tuple, 0, Py_True); Py_INCREF(Py_True);
    PyTuple_SET_ITEM(const_tuple_true_false_tuple, 1, Py_False); Py_INCREF(Py_False);
    const_str_plain_BusConnection = UNSTREAM_STRING_ASCII(&constant_bin[ 1290 ], 13, 1);
    const_str_plain_DBusException = UNSTREAM_STRING_ASCII(&constant_bin[ 2009 ], 13, 1);
    const_str_plain_DBusGMainLoop = UNSTREAM_STRING_ASCII(&constant_bin[ 97173 ], 13, 1);
    const_str_plain_InterfaceInfo = UNSTREAM_STRING_ASCII(&constant_bin[ 6403 ], 13, 1);
    const_str_plain_PROBLEM_TYPES = UNSTREAM_STRING_ASCII(&constant_bin[ 97186 ], 13, 1);
    const_str_plain_SignalMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2527 ], 13, 1);
    const_str_plain_TYPE_PYOBJECT = UNSTREAM_STRING_ASCII(&constant_bin[ 4553 ], 13, 1);
    const_str_plain___docformat__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97199 ], 13, 1);
    const_str_plain___metaclass__ = UNSTREAM_STRING_ASCII(&constant_bin[ 62982 ], 13, 1);
    const_str_plain__initializing = UNSTREAM_STRING_ASCII(&constant_bin[ 97212 ], 13, 1);
    const_str_plain_call_blocking = UNSTREAM_STRING_ASCII(&constant_bin[ 46060 ], 13, 1);
    const_str_plain_error_handler = UNSTREAM_STRING_ASCII(&constant_bin[ 46231 ], 13, 1);
    const_str_plain_fromtimestamp = UNSTREAM_STRING_ASCII(&constant_bin[ 97225 ], 13, 1);
    const_str_plain_get_arguments = UNSTREAM_STRING_ASCII(&constant_bin[ 97238 ], 13, 1);
    const_str_plain_get_dbus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 47350 ], 13, 1);
    const_str_plain_get_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 6258 ], 13, 1);
    const_str_plain_get_namespace = UNSTREAM_STRING_ASCII(&constant_bin[ 97251 ], 13, 1);
    const_str_plain_import_module = UNSTREAM_STRING_ASCII(&constant_bin[ 97264 ], 13, 1);
    const_str_plain_named_service = UNSTREAM_STRING_ASCII(&constant_bin[ 33461 ], 13, 1);
    const_str_plain_reply_handler = UNSTREAM_STRING_ASCII(&constant_bin[ 44388 ], 13, 1);
    const_tuple_int_pos_256_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_int_pos_256_tuple, 0, const_int_pos_256); Py_INCREF(const_int_pos_256);
    const_tuple_str_plain_x_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_x_tuple, 0, const_str_plain_x); Py_INCREF(const_str_plain_x);
    const_tuple_type_object_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_object_tuple, 0, (PyObject *)&PyBaseObject_Type); Py_INCREF((PyObject *)&PyBaseObject_Type);
    const_str_plain_AttributeError = UNSTREAM_STRING_ASCII(&constant_bin[ 7652 ], 14, 1);
    const_str_plain_InvalidProblem = UNSTREAM_STRING_ASCII(&constant_bin[ 80401 ], 14, 1);
    const_str_plain_ProblemWatcher = UNSTREAM_STRING_ASCII(&constant_bin[ 77339 ], 14, 1);
    const_str_plain_TYPE_INTERFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 4033 ], 14, 1);
    const_str_plain___orig_bases__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97277 ], 14, 1);
    const_str_plain__dbus_bindings = UNSTREAM_STRING_ASCII(&constant_bin[ 2970 ], 14, 1);
    const_str_plain_dbus_interface = UNSTREAM_STRING_ASCII(&constant_bin[ 40032 ], 14, 1);
    const_str_plain_is_constructor = UNSTREAM_STRING_ASCII(&constant_bin[ 97291 ], 14, 1);
    const_str_plain_load_overrides = UNSTREAM_STRING_ASCII(&constant_bin[ 5874 ], 14, 1);
    const_slice_int_pos_1_none_none = PySlice_New(const_int_pos_1, Py_None, Py_None);
    const_slice_int_pos_3_none_none = PySlice_New(const_int_pos_3, Py_None, Py_None);
    const_slice_none_int_pos_3_none = PySlice_New(Py_None, const_int_pos_3, Py_None);
    const_str_plain_BUS_DAEMON_NAME = UNSTREAM_STRING_ASCII(&constant_bin[ 1768 ], 15, 1);
    const_str_plain_BUS_DAEMON_PATH = UNSTREAM_STRING_ASCII(&constant_bin[ 1805 ], 15, 1);
    const_str_plain_DynamicImporter = UNSTREAM_STRING_ASCII(&constant_bin[ 6927 ], 15, 1);
    const_str_plain_ValidationError = UNSTREAM_STRING_ASCII(&constant_bin[ 97305 ], 15, 1);
    const_str_plain___annotations__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97320 ], 15, 1);
    const_str_plain___mro_entries__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97335 ], 15, 1);
    const_str_plain_absolute_import = UNSTREAM_STRING_ASCII(&constant_bin[ 97350 ], 15, 1);
    const_str_plain_install_signals = UNSTREAM_STRING_ASCII(&constant_bin[ 97365 ], 15, 1);
    const_str_plain_require_version = UNSTREAM_STRING_ASCII(&constant_bin[ 3648 ], 15, 1);
    const_tuple_str_plain__gi_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain__gi_tuple, 0, const_str_plain__gi); Py_INCREF(const_str_plain__gi);
    const_str_plain_BUS_DAEMON_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 1730 ], 16, 1);
    const_str_plain_ProxyObjectClass = UNSTREAM_STRING_ASCII(&constant_bin[ 97380 ], 16, 1);
    const_str_plain_handler_function = UNSTREAM_STRING_ASCII(&constant_bin[ 39621 ], 16, 1);
    const_str_plain_reStructuredText = UNSTREAM_STRING_ASCII(&constant_bin[ 97396 ], 16, 1);
    const_str_plain_restructuredtext = UNSTREAM_STRING_ASCII(&constant_bin[ 97412 ], 16, 1);
    const_tuple_none_none_none_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_tuple, 2, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain_self_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    const_tuple_str_plain_void_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_void_tuple, 0, const_str_plain_void); Py_INCREF(const_str_plain_void);
    const_tuple_str_plain_warn_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_warn_tuple, 0, const_str_plain_warn); Py_INCREF(const_str_plain_warn);
    const_tuple_type_Exception_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_type_Exception_tuple, 0, (PyObject *)PyExc_Exception); Py_INCREF((PyObject *)PyExc_Exception);
    const_str_plain_MethodCallMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2679 ], 17, 1);
    const_str_plain___class_getitem__ = UNSTREAM_STRING_ASCII(&constant_bin[ 97428 ], 17, 1);
    const_str_plain_inventory_command = UNSTREAM_STRING_ASCII(&constant_bin[ 204 ], 17, 1);
    const_str_plain_require_main_loop = UNSTREAM_STRING_ASCII(&constant_bin[ 97445 ], 17, 1);
    const_str_plain_validate_bus_name = UNSTREAM_STRING_ASCII(&constant_bin[ 1691 ], 17, 1);
    const_tuple_str_plain_clear_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_clear_tuple, 0, const_str_plain_clear); Py_INCREF(const_str_plain_clear);
    const_str_plain_DeprecationWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 1969 ], 18, 1);
    const_str_plain__require_main_loop = UNSTREAM_STRING_ASCII(&constant_bin[ 97444 ], 18, 1);
    const_str_plain_enumerate_versions = UNSTREAM_STRING_ASCII(&constant_bin[ 97462 ], 18, 1);
    const_str_plain_install_properties = UNSTREAM_STRING_ASCII(&constant_bin[ 62368 ], 18, 1);
    const_tuple_str_plain_is_py2_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_is_py2_tuple, 0, const_str_plain_is_py2); Py_INCREF(const_str_plain_is_py2);
    const_str_plain_MethodReturnMessage = UNSTREAM_STRING_ASCII(&constant_bin[ 2745 ], 19, 1);
    const_str_plain_NameExistsException = UNSTREAM_STRING_ASCII(&constant_bin[ 27333 ], 19, 1);
    const_str_plain_ValidationException = UNSTREAM_STRING_ASCII(&constant_bin[ 27258 ], 19, 1);
    const_str_plain_activate_name_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 37971 ], 19, 1);
    const_str_plain_add_signal_receiver = UNSTREAM_STRING_ASCII(&constant_bin[ 32712 ], 19, 1);
    const_str_plain_generate_doc_string = UNSTREAM_STRING_ASCII(&constant_bin[ 5128 ], 19, 1);
    const_str_plain_get_problem_watcher = UNSTREAM_STRING_ASCII(&constant_bin[ 79978 ], 19, 1);
    const_str_plain_validate_error_name = UNSTREAM_STRING_ASCII(&constant_bin[ 26896 ], 19, 1);
    const_tuple_str_dot_int_pos_1_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_dot_int_pos_1_tuple, 0, const_str_dot); Py_INCREF(const_str_dot);
    PyTuple_SET_ITEM(const_tuple_str_dot_int_pos_1_tuple, 1, const_int_pos_1); Py_INCREF(const_int_pos_1);
    const_tuple_str_plain_GObject_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_GObject_tuple, 0, const_str_plain_GObject); Py_INCREF(const_str_plain_GObject);
    const_str_plain_INTROSPECTABLE_IFACE = UNSTREAM_STRING_ASCII(&constant_bin[ 3216 ], 20, 1);
    const_str_plain_get_required_version = UNSTREAM_STRING_ASCII(&constant_bin[ 97480 ], 20, 1);
    const_str_plain_introspection_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5795 ], 20, 1);
    const_str_plain_validate_member_name = UNSTREAM_STRING_ASCII(&constant_bin[ 2246 ], 20, 1);
    const_str_plain_validate_object_path = UNSTREAM_STRING_ASCII(&constant_bin[ 2333 ], 20, 1);
    const_str_plain_DEFAULT_DUMP_LOCATION = UNSTREAM_STRING_ASCII(&constant_bin[ 97500 ], 21, 1);
    const_str_plain_set_sender_name_owner = UNSTREAM_STRING_ASCII(&constant_bin[ 39462 ], 21, 1);
    const_tuple_int_pos_3_int_pos_3_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_pos_3_tuple, 0, const_int_pos_3); Py_INCREF(const_int_pos_3);
    PyTuple_SET_ITEM(const_tuple_int_pos_3_int_pos_3_tuple, 1, const_int_pos_3); Py_INCREF(const_int_pos_3);
    const_tuple_none_none_none_none_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 0, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 2, Py_None); Py_INCREF(Py_None);
    PyTuple_SET_ITEM(const_tuple_none_none_none_none_tuple, 3, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain___class___tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain___class___tuple, 0, const_str_plain___class__); Py_INCREF(const_str_plain___class__);
    const_str_plain_PyGIDeprecationWarning = UNSTREAM_STRING_ASCII(&constant_bin[ 3767 ], 22, 1);
    const_str_plain_UnknownMethodException = UNSTREAM_STRING_ASCII(&constant_bin[ 27309 ], 22, 1);
    const_str_plain__clean_up_signal_match = UNSTREAM_STRING_ASCII(&constant_bin[ 32325 ], 22, 1);
    const_tuple_str_plain_UTF8String_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_UTF8String_tuple, 0, const_str_plain_UTF8String); Py_INCREF(const_str_plain_UTF8String);
    const_tuple_str_plain_pressenter_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_pressenter_tuple, 0, const_str_plain_pressenter); Py_INCREF(const_str_plain_pressenter);
    const_str_plain_validate_interface_name = UNSTREAM_STRING_ASCII(&constant_bin[ 2288 ], 23, 1);
    const_tuple_str_plain_PyGIWarning_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_PyGIWarning_tuple, 0, const_str_plain_PyGIWarning); Py_INCREF(const_str_plain_PyGIWarning);
    const_tuple_str_plain_extend_path_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_extend_path_tuple, 0, const_str_plain_extend_path); Py_INCREF(const_str_plain_extend_path);
    const_str_plain_DBUS_START_REPLY_SUCCESS = UNSTREAM_STRING_ASCII(&constant_bin[ 2112 ], 24, 1);
    const_str_plain_get_introspection_module = UNSTREAM_STRING_ASCII(&constant_bin[ 5791 ], 24, 1);
    const_tuple_str_chr_45_str_plain___tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_chr_45_str_plain___tuple, 0, const_str_chr_45); Py_INCREF(const_str_chr_45);
    PyTuple_SET_ITEM(const_tuple_str_chr_45_str_plain___tuple, 1, const_str_plain__); Py_INCREF(const_str_plain__);
    const_str_plain_follow_name_owner_changes = UNSTREAM_STRING_ASCII(&constant_bin[ 33780 ], 25, 1);
    const_tuple_str_plain_BusConnection_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_BusConnection_tuple, 0, const_str_plain_BusConnection); Py_INCREF(const_str_plain_BusConnection);
    const_tuple_str_plain_DBusException_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_DBusException_tuple, 0, const_str_plain_DBusException); Py_INCREF(const_str_plain_DBusException);
    const_str_plain_process_introspection_data = UNSTREAM_STRING_ASCII(&constant_bin[ 3258 ], 26, 1);
    const_str_plain_submodule_search_locations = UNSTREAM_STRING_ASCII(&constant_bin[ 97521 ], 26, 1);
    const_dict_f154c9a58c9419d7e391901d7b7fe49e = _PyDict_NewPresized( 1 );
    PyDict_SetItem(const_dict_f154c9a58c9419d7e391901d7b7fe49e, const_str_plain_stacklevel, const_int_pos_2);
    assert(PyDict_Size(const_dict_f154c9a58c9419d7e391901d7b7fe49e) == 1);
    const_str_plain_IntrospectionParserException = UNSTREAM_STRING_ASCII(&constant_bin[ 1641 ], 28, 1);
    const_str_plain_MissingErrorHandlerException = UNSTREAM_STRING_ASCII(&constant_bin[ 3139 ], 28, 1);
    const_str_plain_MissingReplyHandlerException = UNSTREAM_STRING_ASCII(&constant_bin[ 3089 ], 28, 1);
    const_str_plain_HANDLER_RESULT_NOT_YET_HANDLED = UNSTREAM_STRING_ASCII(&constant_bin[ 2562 ], 30, 1);
    const_tuple_str_plain_named_service_none_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_named_service_none_tuple, 0, const_str_plain_named_service); Py_INCREF(const_str_plain_named_service);
    PyTuple_SET_ITEM(const_tuple_str_plain_named_service_none_tuple, 1, Py_None); Py_INCREF(Py_None);
    const_tuple_str_plain_self_str_plain_name_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_name_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_name_tuple, 1, const_str_plain_name); Py_INCREF(const_str_plain_name);
    const_tuple_str_plain_self_str_plain_path_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_path_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_path_tuple, 1, const_str_plain_path); Py_INCREF(const_str_plain_path);
    const_str_plain_DBUS_START_REPLY_ALREADY_RUNNING = UNSTREAM_STRING_ASCII(&constant_bin[ 2158 ], 32, 1);
    const_str_digest_09d63a5a61044765cbef1a09e46446f1 = UNSTREAM_STRING_ASCII(&constant_bin[ 97547 ], 38, 0);
    const_str_digest_0b385b2a67f6700b8faf677cdd479207 = UNSTREAM_STRING_ASCII(&constant_bin[ 43257 ], 15, 0);
    const_str_digest_176045277faffdb215e36349ee6bf75e = UNSTREAM_STRING_ASCII(&constant_bin[ 97585 ], 39, 0);
    const_str_digest_18c67c412066bef703396d613a159b4d = UNSTREAM_STRING_ASCII(&constant_bin[ 97624 ], 114, 0);
    const_str_digest_1b131d6ac44490cf7b663211212d8dfa = UNSTREAM_STRING_ASCII(&constant_bin[ 97738 ], 49, 0);
    const_str_digest_25731c733fd74e8333aa29126ce85686 = UNSTREAM_STRING_ASCII(&constant_bin[ 57923 ], 2, 0);
    const_str_digest_286d73d90a388265c9abc0d24ef29c6f = UNSTREAM_STRING_ASCII(&constant_bin[ 31574 ], 29, 0);
    const_str_digest_2dddc6e15ab2dcfb5a2b2205b5654fb4 = UNSTREAM_STRING_ASCII(&constant_bin[ 75881 ], 14, 0);
    const_str_digest_31642840c544e46ac43bf70ce88dbf23 = UNSTREAM_STRING_ASCII(&constant_bin[ 11587 ], 7, 0);
    const_str_digest_3501979af1b70861f5e9d6a0f04129bf = UNSTREAM_STRING_ASCII(&constant_bin[ 12231 ], 3, 0);
    const_str_digest_3aa5bee4de9b0149ae46ffed8a38c6b4 = UNSTREAM_STRING_ASCII(&constant_bin[ 27454 ], 12, 0);
    const_str_digest_3cc8fcb05b60f7b9437930cdc441ce30 = UNSTREAM_STRING_ASCII(&constant_bin[ 97787 ], 52, 0);
    const_str_digest_4289e46f026bf0dd92edd4764f9ca580 = UNSTREAM_STRING_ASCII(&constant_bin[ 97839 ], 105, 0);
    const_str_digest_45e4dde2057b0bf276d6a84f4c917d27 = UNSTREAM_STRING_ASCII(&constant_bin[ 26617 ], 7, 0);
    const_str_digest_58961c73026e70b23b08cf381b49e04e = UNSTREAM_STRING_ASCII(&constant_bin[ 97944 ], 15, 0);
    const_str_digest_6090a95f7b926ecd6061b143b7cad52f = UNSTREAM_STRING_ASCII(&constant_bin[ 97959 ], 51, 0);
    const_str_digest_62223e4c0fc7bcb5885146e43f1fb665 = UNSTREAM_STRING_ASCII(&constant_bin[ 30804 ], 10, 0);
    const_str_digest_66f7aeb02c13e91a30a18f0ea911888b = UNSTREAM_STRING_ASCII(&constant_bin[ 58759 ], 13, 0);
    const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb = UNSTREAM_STRING_ASCII(&constant_bin[ 98010 ], 25, 0);
    const_str_digest_75fd71b1edada749c2ef7ac810062295 = UNSTREAM_STRING_ASCII(&constant_bin[ 98035 ], 46, 0);
    const_str_digest_79ed2cac4e638f0656fd263c1190bdb0 = UNSTREAM_STRING_ASCII(&constant_bin[ 28012 ], 8, 0);
    const_str_digest_8e2db9d493d0360a27a3bf19583a3201 = UNSTREAM_STRING_ASCII(&constant_bin[ 34573 ], 12, 0);
    const_str_digest_9816e8d1552296af90d250823c964059 = UNSTREAM_STRING_ASCII(&constant_bin[ 98081 ], 46, 0);
    const_str_digest_a70d2bed936523093700e5558854519a = UNSTREAM_STRING_ASCII(&constant_bin[ 98127 ], 25, 0);
    const_str_digest_adc474dd61fbd736d69c1bac5d9712e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 98152 ], 47, 0);
    const_str_digest_b0cc034d9177fde48a3b44ac122139d9 = UNSTREAM_STRING_ASCII(&constant_bin[ 43238 ], 6, 0);
    const_str_digest_b45a3c6f685a3991de51197626bab5ca = UNSTREAM_STRING_ASCII(&constant_bin[ 42502 ], 13, 0);
    const_str_digest_b9c4baf879ebd882d40843df3a4dead7 = UNSTREAM_STRING_ASCII(&constant_bin[ 15928 ], 2, 1);
    const_str_digest_c075052d723d6707083e869a0e3659bb = UNSTREAM_STRING_ASCII(&constant_bin[ 98199 ], 5, 0);
    const_str_digest_d7a2d3682b691f7fb6d75512d991b529 = UNSTREAM_STRING_ASCII(&constant_bin[ 98204 ], 13, 0);
    const_str_digest_db35ab94a03c3cbeb13cbe2a1d728b77 = UNSTREAM_STRING_ASCII(&constant_bin[ 11271 ], 2, 0);
    const_str_digest_e48610c30fffad33f2054d9dca0792b3 = UNSTREAM_STRING_ASCII(&constant_bin[ 47120 ], 15, 0);
    const_str_digest_ec911d7d8aa19d9c1e00a67b34952d6e = UNSTREAM_STRING_ASCII(&constant_bin[ 73182 ], 12, 0);
    const_str_digest_f570069e0d46f80dd06443468800a290 = UNSTREAM_STRING_ASCII(&constant_bin[ 23792 ], 4, 0);
    const_str_digest_fcf040720b88d60da4ce975010c44a3a = UNSTREAM_STRING_ASCII(&constant_bin[ 98217 ], 38, 0);
    const_str_digest_fdd1f239b4f3ffd6efcccf00e4a637e0 = UNSTREAM_STRING_ASCII(&constant_bin[ 98255 ], 48, 0);
    const_tuple_str_plain_args_str_plain_kwargs_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_args_str_plain_kwargs_tuple, 0, const_str_plain_args); Py_INCREF(const_str_plain_args);
    PyTuple_SET_ITEM(const_tuple_str_plain_args_str_plain_kwargs_tuple, 1, const_str_plain_kwargs); Py_INCREF(const_str_plain_kwargs);
    const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple = PyTuple_New(4);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 0, const_str_plain_Bus); Py_INCREF(const_str_plain_Bus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 1, const_str_plain_SystemBus); Py_INCREF(const_str_plain_SystemBus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 2, const_str_plain_SessionBus); Py_INCREF(const_str_plain_SessionBus);
    PyTuple_SET_ITEM(const_tuple_76ee81f3638eaf5a352e7276367934cb_tuple, 3, const_str_plain_StarterBus); Py_INCREF(const_str_plain_StarterBus);
    const_tuple_str_plain_PyGIDeprecationWarning_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_plain_PyGIDeprecationWarning_tuple, 0, const_str_plain_PyGIDeprecationWarning); Py_INCREF(const_str_plain_PyGIDeprecationWarning);
    const_tuple_str_plain_self_str_plain_bus_name_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_bus_name_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_bus_name_tuple, 1, const_str_plain_bus_name); Py_INCREF(const_str_plain_bus_name);
    const_tuple_str_plain_self_str_plain_instance_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_tuple, 1, const_str_plain_instance); Py_INCREF(const_str_plain_instance);
    const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_71b716a2e5991dc1dd383ac4073f8ceb_tuple, 0, const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb); Py_INCREF(const_str_digest_71b716a2e5991dc1dd383ac4073f8ceb);
    const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(const_tuple_str_digest_c075052d723d6707083e869a0e3659bb_tuple, 0, const_str_digest_c075052d723d6707083e869a0e3659bb); Py_INCREF(const_str_digest_c075052d723d6707083e869a0e3659bb);
    const_tuple_anon_function_anon_builtin_function_or_method_tuple = PyTuple_New(2);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 0, (PyObject *)&PyFunction_Type); Py_INCREF((PyObject *)&PyFunction_Type);
    PyTuple_SET_ITEM(const_tuple_anon_function_anon_builtin_function_or_method_tuple, 1, (PyObject *)&PyCFunction_Type); Py_INCREF((PyObject *)&PyCFunction_Type);
    const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple = PyTuple_New(3);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 0, const_str_plain_self); Py_INCREF(const_str_plain_self);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 1, const_str_plain_instance); Py_INCREF(const_str_plain_instance);
    PyTuple_SET_ITEM(const_tuple_str_plain_self_str_plain_instance_str_plain_owner_tuple, 2, const_str_plain_owner); Py_INCREF(const_str_plain_owner);

#if _NUITKA_EXE
    /* Set the "sys.executable" path to the original CPython executable. */
    PySys_SetObject(
        (char *)"executable",
        const_str_digest_58961c73026e70b23b08cf381b49e04e
    );

#ifndef _NUITKA_STANDALONE
    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.prefix" path to the original one. */
    PySys_SetObject(
        (char *)"exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );


#if PYTHON_VERSION >= 300
    /* Set the "sys.base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

    /* Set the "sys.exec_base_prefix" path to the original one. */
    PySys_SetObject(
        (char *)"base_exec_prefix",
        const_str_digest_f570069e0d46f80dd06443468800a290
    );

#endif
#endif
#endif

    static PyTypeObject Nuitka_VersionInfoType;

    // Same fields as "sys.version_info" except no serial number.
    static PyStructSequence_Field Nuitka_VersionInfoFields[] = {
        {(char *)"major", (char *)"Major release number"},
        {(char *)"minor", (char *)"Minor release number"},
        {(char *)"micro", (char *)"Micro release number"},
        {(char *)"releaselevel", (char *)"'alpha', 'beta', 'candidate', or 'release'"},
        {0}
    };

    static PyStructSequence_Desc Nuitka_VersionInfoDesc = {
        (char *)"__nuitka_version__",                                    /* name */
        (char *)"__compiled__\n\nVersion information as a named tuple.", /* doc */
        Nuitka_VersionInfoFields,                                        /* fields */
        4
    };

    PyStructSequence_InitType(&Nuitka_VersionInfoType, &Nuitka_VersionInfoDesc);

    Nuitka_dunder_compiled_value = PyStructSequence_New(&Nuitka_VersionInfoType);
    assert(Nuitka_dunder_compiled_value != NULL);

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 0, PyInt_FromLong(0));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 1, PyInt_FromLong(6));
    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 2, PyInt_FromLong(9));

    PyStructSequence_SET_ITEM(Nuitka_dunder_compiled_value, 3, Nuitka_String_FromString("candidate"));

    // Prevent users from creating the Nuitka version type object.
    Nuitka_VersionInfoType.tp_init = NULL;
    Nuitka_VersionInfoType.tp_new = NULL;


}

// In debug mode we can check that the constants were not tampered with in any
// given moment. We typically do it at program exit, but we can add extra calls
// for sanity.
#ifndef __NUITKA_NO_ASSERT__
void checkGlobalConstants(void) {

}
#endif

void createGlobalConstants(void) {
    if (_sentinel_value == NULL) {
#if PYTHON_VERSION < 300
        _sentinel_value = PyCObject_FromVoidPtr(NULL, NULL);
#else
        // The NULL value is not allowed for a capsule, so use something else.
        _sentinel_value = PyCapsule_New((void *)27, "sentinel", NULL);
#endif
        assert(_sentinel_value);

        _createGlobalConstants();
    }
}
